<?php

$usersList = "
Aarav Sharma – aarav123@sharklasers.com
Vivaan Patel – vivaan123@sharklasers.com
Aditya Singh – aditya123@sharklasers.com
Arjun Gupta – arjun123@sharklasers.com
Sai Reddy – sai123@sharklasers.com
Krishna Nair – krishna123@sharklasers.com
Rahul Mehta – rahul123@sharklasers.com
Karthik Iyer – karthik123@sharklasers.com
Rohan Das – rohan123@sharklasers.com
Mohan Pillai – mohan123@sharklasers.com
Ananya Sharma – ananya123@sharklasers.com
Diya Patel – diya123@sharklasers.com
Isha Singh – isha123@sharklasers.com
Kavya Gupta – kavya123@sharklasers.com
Sneha Reddy – sneha123@sharklasers.com
Meera Nair – meera123@sharklasers.com
Pooja Mehta – pooja123@sharklasers.com
Aishwarya Iyer – aishwarya123@sharklasers.com
Neha Das – neha123@sharklasers.com
Lakshmi Pillai – lakshmi123@sharklasers.com
Varun Sharma – varun123@sharklasers.com
Nikhil Patel – nikhil123@sharklasers.com
Suresh Singh – suresh123@sharklasers.com
Rajesh Gupta – rajesh123@sharklasers.com
Ajay Reddy – ajay123@sharklasers.com
Manoj Nair – manoj123@sharklasers.com
Deepak Mehta – deepak123@sharklasers.com
Sanjay Iyer – sanjay123@sharklasers.com
Vijay Das – vijay123@sharklasers.com
Prakash Pillai – prakash123@sharklasers.com
Priya Sharma – priya123@sharklasers.com
Ritu Patel – ritu123@sharklasers.com
Swati Singh – swati123@sharklasers.com
Nisha Gupta – nisha123@sharklasers.com
Komal Reddy – komal123@sharklasers.com
Rekha Nair – rekha123@sharklasers.com
Shalini Mehta – shalini123@sharklasers.com
Divya Iyer – divya123@sharklasers.com
Poonam Das – poonam123@sharklasers.com
Radha Pillai – radha123@sharklasers.com
Akash Sharma – akash123@sharklasers.com
Imran Patel – imran123@sharklasers.com
Yusuf Singh – yusuf123@sharklasers.com
Sameer Gupta – sameer123@sharklasers.com
Farhan Reddy – farhan123@sharklasers.com
Zaid Nair – zaid123@sharklasers.com
Arif Mehta – arif123@sharklasers.com
Salman Iyer – salman123@sharklasers.com
Javed Das – javed123@sharklasers.com
Rizwan Pillai – rizwan123@sharklasers.com
Tanya Sharma – tanya123@sharklasers.com
Alia Patel – alia123@sharklasers.com
Sara Singh – sara123@sharklasers.com
Hina Gupta – hina123@sharklasers.com
Sana Reddy – sana123@sharklasers.com
Fatima Nair – fatima123@sharklasers.com
Zoya Mehta – zoya123@sharklasers.com
Amina Iyer – amina123@sharklasers.com
Nazia Das – nazia123@sharklasers.com
Shabana Pillai – shabana123@sharklasers.com
Dev Sharma – dev123@sharklasers.com
Harsh Patel – harsh123@sharklasers.com
Kunal Singh – kunal123@sharklasers.com
Tarun Gupta – tarun123@sharklasers.com
Gaurav Reddy – gaurav123@sharklasers.com
Lokesh Nair – lokesh123@sharklasers.com
Naveen Mehta – naveen123@sharklasers.com
Sandeep Iyer – sandeep123@sharklasers.com
Amit Das – amit123@sharklasers.com
Bharat Pillai – bharat123@sharklasers.com
Riya Sharma – riya123@sharklasers.com
Siya Patel – siya123@sharklasers.com
Anjali Singh – anjali123@sharklasers.com
Preeti Gupta – preeti123@sharklasers.com
Jyoti Reddy – jyoti123@sharklasers.com
Usha Nair – usha123@sharklasers.com
Lata Mehta – lata123@sharklasers.com
Bhavna Iyer – bhavna123@sharklasers.com
Kiran Das – kiran123@sharklasers.com
Sudha Pillai – sudha123@sharklasers.com
Om Sharma – om123@sharklasers.com
Tejas Patel – tejas123@sharklasers.com
Dhruv Singh – dhruv123@sharklasers.com
Yash Gupta – yash123@sharklasers.com
Ritesh Reddy – ritesh123@sharklasers.com
Vignesh Nair – vignesh123@sharklasers.com
Ashwin Mehta – ashwin123@sharklasers.com
Surya Iyer – surya123@sharklasers.com
Naveed Das – naveed123@sharklasers.com
Faizal Pillai – faizal123@sharklasers.com
Aarti Sharma – aarti123@sharklasers.com
Deepa Patel – deepa123@sharklasers.com
Monika Singh – monika123@sharklasers.com
Rachna Gupta – rachna123@sharklasers.com
Sushma Reddy – sushma123@sharklasers.com
Geeta Nair – geeta123@sharklasers.com
Hema Mehta – hema123@sharklasers.com
Revathi Iyer – revathi123@sharklasers.com
Sunita Das – sunita123@sharklasers.com
Malathi Pillai – malathi123@sharklasers.com
Abhishek Verma – abhishek201@sharklasers.com
Anand Kulkarni – anand202@sharklasers.com
Anil Bhat – anil203@sharklasers.com
Ashok Chawla – ashok204@sharklasers.com
Balaji Menon – balaji205@sharklasers.com
Bharat Joshi – bharat206@sharklasers.com
Chandru Rao – chandru207@sharklasers.com
Dhanush Sinha – dhanush208@sharklasers.com
Dinesh Kapoor – dinesh209@sharklasers.com
Ganesh Malhotra – ganesh210@sharklasers.com
Gokul Mishra – gokul211@sharklasers.com
Hari Prasad – hari212@sharklasers.com
Harish Saxena – harish213@sharklasers.com
Jagan Yadav – jagan214@sharklasers.com
Jeevan Arora – jeevan215@sharklasers.com
Kiran Bansal – kiran216@sharklasers.com
Loknath Jain – loknath217@sharklasers.com
Madhav Tiwari – madhav218@sharklasers.com
Mahesh Dubey – mahesh219@sharklasers.com
Mukesh Chandra – mukesh220@sharklasers.com
Naresh Solanki – naresh221@sharklasers.com
Nitin Agrawal – nitin222@sharklasers.com
Pavan Rawat – pavan223@sharklasers.com
Pradeep Jha – pradeep224@sharklasers.com
Pranav Shetty – pranav225@sharklasers.com
Rajiv Kohli – rajiv226@sharklasers.com
Rakesh Bhardwaj – rakesh227@sharklasers.com
Ramesh Nayak – ramesh228@sharklasers.com
Roshan Lal – roshan229@sharklasers.com
Sachin Purohit – sachin230@sharklasers.com
Santhosh Walia – santhosh231@sharklasers.com
Shankar Khanna – shankar232@sharklasers.com
Srinivas Oberoi – srinivas233@sharklasers.com
Sudeep Bedi – sudeep234@sharklasers.com
Sunil Vyas – sunil235@sharklasers.com
Suresh Parmar – suresh236@sharklasers.com
Uday Goswami – uday237@sharklasers.com
Vasant Dutta – vasant238@sharklasers.com
Venkat Bakshi – venkat239@sharklasers.com
Vinod Choksi – vinod240@sharklasers.com
Aakash Sehgal – aakash241@sharklasers.com
Amar Jindal – amar242@sharklasers.com
Anoop Talwar – anoop243@sharklasers.com
Bhavesh Ahuja – bhavesh244@sharklasers.com
Darshan Kaul – darshan245@sharklasers.com
Eshwar Luthra – eshwar246@sharklasers.com
Girish Tomar – girish247@sharklasers.com
Hemant Anand – hemant248@sharklasers.com
Inder Chhabra – inder249@sharklasers.com
Jatin Batra – jatin250@sharklasers.com
Aditi Sharma – aditi251@sharklasers.com
Akanksha Patel – akanksha252@sharklasers.com
Amrita Singh – amrita253@sharklasers.com
Ankita Gupta – ankita254@sharklasers.com
Bhavana Reddy – bhavana255@sharklasers.com
Charu Nair – charu256@sharklasers.com
Deepika Mehta – deepika257@sharklasers.com
Esha Iyer – esha258@sharklasers.com
Garima Das – garima259@sharklasers.com
Harini Pillai – harini260@sharklasers.com
Ishita Verma – ishita261@sharklasers.com
Janani Kulkarni – janani262@sharklasers.com
Kavitha Bhat – kavitha263@sharklasers.com
Lalitha Chawla – lalitha264@sharklasers.com
Madhuri Menon – madhuri265@sharklasers.com
Namrata Joshi – namrata266@sharklasers.com
Oviya Rao – oviya267@sharklasers.com
Pallavi Sinha – pallavi268@sharklasers.com
Radhika Kapoor – radhika269@sharklasers.com
Sangeetha Malhotra – sangeetha270@sharklasers.com
Shreya Mishra – shreya271@sharklasers.com
Tanvi Prasad – tanvi272@sharklasers.com
Uma Saxena – uma273@sharklasers.com
Vaishnavi Yadav – vaishnavi274@sharklasers.com
Yamini Arora – yamini275@sharklasers.com
Zareen Bansal – zareen276@sharklasers.com
Ahalya Jain – ahalya277@sharklasers.com
Bindu Tiwari – bindu278@sharklasers.com
Chitra Dubey – chitra279@sharklasers.com
Devika Chandra – devika280@sharklasers.com
Elakkiya Solanki – elakkiya281@sharklasers.com
Falguni Agrawal – falguni282@sharklasers.com
Gayathri Rawat – gayathri283@sharklasers.com
Hiral Jha – hiral284@sharklasers.com
Indhu Shetty – indhu285@sharklasers.com
Jyothi Kohli – jyothi286@sharklasers.com
Kalpana Bhardwaj – kalpana287@sharklasers.com
Leela Nayak – leela288@sharklasers.com
Mamta Lal – mamta289@sharklasers.com
Nandhini Purohit – nandhini290@sharklasers.com
Oormila Walia – oormila291@sharklasers.com
Parvathi Khanna – parvathi292@sharklasers.com
Queenie Oberoi – queenie293@sharklasers.com
Renu Bedi – renu294@sharklasers.com
Savitha Vyas – savitha295@sharklasers.com
Trisha Parmar – trisha296@sharklasers.com
Urmila Goswami – urmila297@sharklasers.com
Vidya Dutta – vidya298@sharklasers.com
Wincy Bakshi – wincy299@sharklasers.com
Yashika Choksi – yashika300@sharklasers.com
Adarsh Sehgal – adarsh301@sharklasers.com
Bhanu Jindal – bhanu302@sharklasers.com
Chetan Talwar – chetan303@sharklasers.com
Devraj Ahuja – devraj304@sharklasers.com
Eklavya Kaul – eklavya305@sharklasers.com
Faisal Luthra – faisal306@sharklasers.com
Gautham Tomar – gautham307@sharklasers.com
Himanshu Anand – himanshu308@sharklasers.com
Ishwar Chhabra – ishwar309@sharklasers.com
Jagan Batra – jagan310@sharklasers.com
Keshav Sharma – keshav311@sharklasers.com
Lakshman Patel – lakshman312@sharklasers.com
Manav Singh – manav313@sharklasers.com
Nandan Gupta – nandan314@sharklasers.com
Omkar Reddy – omkar315@sharklasers.com
Prithvi Nair – prithvi316@sharklasers.com
Raghu Mehta – raghu317@sharklasers.com
Siddharth Iyer – siddharth318@sharklasers.com
Tejaswin Das – tejaswin319@sharklasers.com
Umesh Pillai – umesh320@sharklasers.com
Vaibhav Verma – vaibhav321@sharklasers.com
Wasim Kulkarni – wasim322@sharklasers.com
Yuvraj Bhat – yuvraj323@sharklasers.com
Zubin Chawla – zubin324@sharklasers.com
Aarush Menon – aarush325@sharklasers.com
Bhargav Joshi – bhargav326@sharklasers.com
Chirag Rao – chirag327@sharklasers.com
Deven Sinha – deven328@sharklasers.com
Eesan Kapoor – eesan329@sharklasers.com
Farooq Malhotra – farooq330@sharklasers.com
Gagan Mishra – gagan331@sharklasers.com
Hardik Prasad – hardik332@sharklasers.com
Irfan Saxena – irfan333@sharklasers.com
Jitesh Yadav – jitesh334@sharklasers.com
Kunal Arora – kunal335@sharklasers.com
Lalit Bansal – lalit336@sharklasers.com
Mohit Jain – mohit337@sharklasers.com
Naren Tiwari – naren338@sharklasers.com
Piyush Dubey – piyush339@sharklasers.com
Rituraj Chandra – rituraj340@sharklasers.com
Sagar Solanki – sagar341@sharklasers.com
Tushar Agrawal – tushar342@sharklasers.com
Utkarsh Rawat – utkarsh343@sharklasers.com
Vivek Jha – vivek344@sharklasers.com
Waseem Shetty – waseem345@sharklasers.com
Yatin Kohli – yatin346@sharklasers.com
Zaid Bhardwaj – zaid347@sharklasers.com
Abhay Nayak – abhay348@sharklasers.com
Brijesh Lal – brijesh349@sharklasers.com
Cyril Purohit – cyril350@sharklasers.com
Daksh Walia – daksh351@sharklasers.com
Eshaan Khanna – eshaan352@sharklasers.com
Firoz Oberoi – firoz353@sharklasers.com
Gireesh Bedi – gireesh354@sharklasers.com
Hrithik Vyas – hrithik355@sharklasers.com
Ilesh Parmar – ilesh356@sharklasers.com
Jai Goswami – jai357@sharklasers.com
Karthikeyan Dutta – karthikeyan358@sharklasers.com
Lokesh Bakshi – lokesh359@sharklasers.com
Mitesh Choksi – mitesh360@sharklasers.com
Nikhilesh Sehgal – nikhilesh361@sharklasers.com
Ojas Jindal – ojas362@sharklasers.com
Praveen Talwar – praveen363@sharklasers.com
Qadir Ahuja – qadir364@sharklasers.com
Ranjith Kaul – ranjith365@sharklasers.com
Sharath Luthra – sharath366@sharklasers.com
Tharun Tomar – tharun367@sharklasers.com
Udayan Anand – udayan368@sharklasers.com
Varadharajan Chhabra – varadharajan369@sharklasers.com
Yoganand Batra – yoganand370@sharklasers.com
Ayesha Sharma – ayesha371@sharklasers.com
Bhavya Patel – bhavya372@sharklasers.com
Chandini Singh – chandini373@sharklasers.com
Damini Gupta – damini374@sharklasers.com
Eshita Reddy – eshita375@sharklasers.com
Fathima Nair – fathima376@sharklasers.com
Grishma Mehta – grishma377@sharklasers.com
Hansika Iyer – hansika378@sharklasers.com
Ipsita Das – ipsita379@sharklasers.com
Jhanvi Pillai – jhanvi380@sharklasers.com
Khushi Verma – khushi381@sharklasers.com
Lavanya Kulkarni – lavanya382@sharklasers.com
Manya Bhat – manya383@sharklasers.com
Navya Chawla – navya384@sharklasers.com
Ojal Menon – ojal385@sharklasers.com
Prachi Joshi – prachi386@sharklasers.com
Roshni Rao – roshni387@sharklasers.com
Simran Sinha – simran388@sharklasers.com
Tanisha Kapoor – tanisha389@sharklasers.com
Urvashi Malhotra – urvashi390@sharklasers.com
Veda Mishra – veda391@sharklasers.com
Wamika Prasad – wamika392@sharklasers.com
Yutika Saxena – yutika393@sharklasers.com
Zinal Yadav – zinal394@sharklasers.com
Arohi Arora – arohi395@sharklasers.com
Bhavika Bansal – bhavika396@sharklasers.com
Charvi Jain – charvi397@sharklasers.com
Driti Tiwari – driti398@sharklasers.com
Ekta Dubey – ekta399@sharklasers.com
Falak Chandra – falak400@sharklasers.com
";

$lines = explode(PHP_EOL, trim($usersList));

foreach ($lines as $line) {
    if (empty(trim($line))) continue;
    
    // Replace the specific long dash from the prompt with a standard hyphen for easier splitting
    $line = str_replace('–', '-', $line);
    
    $parts = explode('-', $line);
    
    if (count($parts) >= 2) {
        $name = trim($parts[0]);
        $email = trim($parts[1]);
        
        $user = App\Models\User::where('email', $email)->first();
        if (!$user) {
            App\Models\User::create([
                'name' => $name,
                'email' => $email,
                'password' => bcrypt('Test123*'),
                'role' => 'user',
                'status' => 'Active',
                'email_verified_at' => now(),
            ]);
            echo "Created: $email\n";
        } else {
            echo "Exists: $email\n";
        }
    }
}
