const fs = require('fs');

const categories = {
  'H1B Visa discussion': [
    { title: 'L1A to H1B transition', content: 'What are the pros and cons of moving from L1A to H1B?', replies: ['H1B allows you to change employers, which L1A does not.', 'You lose the fast-track EB1C green card option if you switch from L1A.', 'H1B has a 6-year limit, but L1A has a 7-year limit. Consider your long-term plan.'] },
    { title: 'H1B stamping in Frankfurt', content: 'Can third-country nationals get H1B stamping in Germany?', replies: ['Yes, Frankfurt accepts TCNs, but appointment wait times can be long.', 'Make sure you have a valid Schengen visa to enter Germany first!', 'I did mine there last month. Very smooth process, passport returned in 3 days.'] },
    { title: 'F1 OPT expiring, no H1B', content: 'Didn\'t get picked in the lottery for the 3rd time. What are my options?', replies: ['Look into Day 1 CPT programs, but be aware of the risks.', 'Consider an L1 transfer by working for your company\'s overseas branch for a year.', 'You could try applying for the O-1 visa if you have extraordinary ability or publications.'] },
    { title: 'H1B dependent employer rules', content: 'My new offer is from an H1B dependent employer. Should I be worried?', replies: ['They face stricter scrutiny from the DOL, but if it\'s a legit role, it\'s fine.', 'Make sure they are offering the prevailing wage. Dependent employers are watched closely.', 'It just means they have a high percentage of H1B workers. Not inherently bad.'] },
    { title: 'Traveling while H1B extension is pending', content: 'Can I travel to India while my H1B extension is pending with USCIS?', replies: ['If your current visa stamp and I-94 are still valid, yes. Otherwise, no.', 'It is highly unadvisable to travel while an extension is pending. It might be considered abandoned.', 'Upgrade to premium processing, wait for approval, get stamped, then travel.'] },
    { title: 'H1B and side hustles', content: 'Can I drive for Uber or do DoorDash on an H1B?', replies: ['Absolutely not. It is a violation of your visa status.', 'H1B is strictly tied to the sponsoring employer. No unauthorized gig work.', 'If caught, you could face deportation and a ban from re-entering.'] },
    { title: 'Changing jobs right after H1B approval', content: 'Got my H1B approved starting Oct 1. Can I transfer it immediately?', replies: ['You should ideally work for the sponsoring employer for at least a few pay periods.', 'A transfer before Oct 1 is technically possible but highly complex and risky.', 'Wait until October, get a couple of paystubs, then initiate the transfer.'] },
    { title: 'H1B RFE for wage level', content: 'Got an RFE stating Wage Level 1 is not appropriate for the role. Advice?', replies: ['Your lawyers need to prove the role is entry-level but still requires a specialized degree.', 'This was common a few years ago. Provide detailed job duties distinguishing it from higher levels.', 'Sometimes it\'s easier for the employer to amend the LCA to Wage Level 2 and pay more.'] },
    { title: 'Spouse on H4 working illegally', content: 'What happens if an H4 dependent works without an EAD?', replies: ['It is a serious violation. It can jeopardize both the H4 and the primary H1B status.', 'Do not do this. It will cause major issues during the Green Card process.', 'Unauthorized work is a deportable offense. Get the EAD first.'] },
    { title: 'H1B renewal without paystubs', content: 'I was on unpaid leave for medical reasons. Will this affect my renewal?', replies: ['Medical leave under FMLA is protected and shouldn\'t affect your status.', 'Have documentation ready from your doctor and HR proving it was authorized leave.', 'Usually, as long as the employer-employee relationship maintained, it\'s okay.'] },
    { title: 'Can I invest in stocks on H1B?', content: 'Is day trading allowed on an H1B visa?', replies: ['Passive investing is allowed, but day trading as a primary source of income is a gray area.', 'Buying and holding stocks or index funds is perfectly fine and encouraged.', 'Don\'t make it look like a full-time job. A few trades a week is generally safe.'] },
    { title: 'H1B grace period used up', content: 'Used my 60 days, switched to B2, now got an offer. Process?', replies: ['The new employer files an H1B petition with a change of status from B2 to H1B.', 'You must wait for the H1B to be approved before you can start working. No receipt-notice work.', 'Premium processing is your friend here to get back to work quickly.'] },
    { title: 'Lost passport with H1B visa', content: 'My passport was stolen. What do I do about my H1B visa?', replies: ['File a police report immediately. Then contact your embassy for a new passport.', 'The actual visa stamp is gone. You will need to apply for a new stamp next time you leave the US.', 'Your status is maintained by your I-797 and I-94, not the physical stamp. You are legally fine here.'] },
    { title: 'H1B prevailing wage determination', content: 'How long are PWDs taking right now for PERM?', replies: ['Currently taking about 6-7 months just for the PWD. It\'s ridiculous.', 'Mine took 185 days. The DOL is severely backlogged.', 'Plan for at least 2 years total for the entire PERM process right now.'] },
    { title: 'Changing from H1B to F1 for PhD', content: 'Thinking of quitting my job to do a PhD. How hard is the transition?', replies: ['Filing a Change of Status from H1B to F1 is straightforward but takes months. Plan ahead.', 'You might have an issue proving non-immigrant intent for F1 if you already have an I-140.', 'It\'s often faster to leave the US and get an F1 stamp at a consulate.'] },
    { title: 'H1B cap exempt jobs', content: 'Are universities the only cap-exempt employers?', replies: ['No, non-profit research organizations and government research organizations are also exempt.', 'Some hospitals affiliated with universities also qualify for cap-exempt H1Bs.', 'Remember, you cannot transfer a cap-exempt H1B to a for-profit company without going through the lottery.'] },
    { title: 'Severance pay and H1B status', content: 'Does receiving severance extend my H1B status?', replies: ['No. Your status ends on your last day of actual work, not when severance stops.', 'Severance is just money owed. It does not maintain the employer-employee relationship.', 'The 60-day grace period starts the day after your last working day.'] },
    { title: 'H1B Visa revocation by employer', content: 'If my employer revokes my H1B after a layoff, do I lose my grace period?', replies: ['No, the 60-day grace period is granted by regulation. The employer revoking the petition does not cancel it.', 'Employers are legally required to notify USCIS to revoke the petition when you leave.', 'You still have the 60 days from your last date of employment.'] },
    { title: 'Buying a business on H1B', content: 'Can I buy a franchise (like Subway) while on H1B?', replies: ['You can own it, but you cannot work there or manage it. You must hire a manager.', 'It\'s very risky. Even doing payroll or sweeping the floor is a visa violation.', 'Consult an attorney. You need to structure it carefully as a passive investment.'] },
    { title: 'H1B stamping delays in India', content: 'Why are Dropbox cases taking so long in India right now?', replies: ['Heavy volume and staffing shortages at the consulates.', 'If your case requires extra verification (PIMS), it adds another 1-2 weeks.', 'Plan for at least 3-4 weeks to be safe if you travel to India.'] }
  ],
  'Indian Cooking': [
    { title: 'Making perfect crispy Dosa', content: 'My dosas are always soft. How do I make them crispy like restaurants?', replies: ['Add a little bit of poha or fenugreek seeds (methi) when grinding the batter.', 'The tawa needs to be hot when you pour, but lower the heat to medium to cook it crisp.', 'A dash of sugar in the batter helps it caramelize and get that golden brown color.'] },
    { title: 'Best substitute for Ghee', content: 'I am vegan but want to cook Indian food. What is the best ghee substitute?', replies: ['Coconut oil works well for South Indian dishes. For North Indian, try a neutral oil with a drop of butter extract.', 'Miyokos vegan butter actually browns well and gives a decent flavor.', 'Just use a good quality avocado oil or grapeseed oil. The spices will provide enough flavor.'] },
    { title: 'How to fix too much salt in curry', content: 'I accidentally over-salted my chicken curry. How can I fix it?', replies: ['Add a peeled, quartered raw potato and simmer for 15 mins. It will absorb the salt.', 'Add a splash of heavy cream or yogurt to balance the flavors.', 'A little bit of sugar or a squeeze of lemon juice can help mask the saltiness.'] },
    { title: 'Stovetop vs Oven for Naan', content: 'Can you make decent naan on a stovetop without a tandoor?', replies: ['Yes! Use a cast iron skillet. Wet one side of the naan, stick it to the pan, then flip the pan upside down over the flame.', 'The inverted tawa method is the closest you will get to tandoori naan at home.', 'Baking them on a pizza stone in a very hot oven (500F) also works great.'] },
    { title: 'Making soft Gulab Jamuns', content: 'Mine always have a hard lump in the center. What am I doing wrong?', replies: ['You are kneading the dough too much. It should be just brought together gently, not kneaded like roti dough.', 'The oil might be too hot. Fry them on low-medium heat so they cook all the way through.', 'Make sure the syrup is warm, not boiling, when you drop them in.'] },
    { title: 'Best blender for Indian cooking in US', content: 'Vitamix, Blendtec, or an Indian mixer grinder like Preethi?', replies: ['Vitamix is a beast and blends everything smooth, but an Indian mixie is better for dry grinding spices and small quantities.', 'I have a Preethi Zodiac and it is perfect for dosa batter and chutneys.', 'Ninja is a good budget alternative, but nothing beats a heavy-duty Indian mixer grinder for authentic textures.'] },
    { title: 'How to prevent yogurt from curdling in curries', content: 'Every time I add yogurt to a hot gravy, it splits. Help!', replies: ['Turn the heat all the way down or off before adding the yogurt. Stir continuously.', 'Whisk the yogurt well with a little bit of besan (gram flour) or cornstarch before adding it.', 'Temper the yogurt by mixing a spoonful of the hot gravy into it before pouring the whole thing into the pot.'] },
    { title: 'Difference between Garam Masala and Curry Powder', content: 'Is "curry powder" from the American grocery store the same as garam masala?', replies: ['Absolutely not. Curry powder is a British invention and usually heavy on turmeric. Garam masala is a warming spice blend without turmeric.', 'Never use generic "curry powder" for authentic Indian recipes. It tastes completely different.', 'Always use specific spices or a good quality garam masala for North Indian dishes.'] },
    { title: 'Making Chole dark brown', content: 'My chole always looks yellow. How do restaurants get that dark, rich color?', replies: ['Boil the chickpeas with a couple of tea bags or dried amla (gooseberry). It gives them the dark color.', 'Roast your onions and tomatoes until they are very dark before pureeing them.', 'Use an iron kadai to cook the chole. The iron reacts with the spices and darkens the dish.'] },
    { title: 'Best oil for deep frying Indian snacks', content: 'Canola, peanut, or vegetable oil for samosas and pakoras?', replies: ['Peanut oil is the best because it has a high smoke point and a neutral flavor.', 'Canola is fine and cheap, but sometimes leaves a slightly fishy smell when heated too much.', 'I use regular vegetable oil or sunflower oil. Avoid olive oil for deep frying.'] },
    { title: 'How to store ginger garlic paste', content: 'My homemade paste turns green after a week in the fridge. Is it safe?', replies: ['It is safe, just an enzymatic reaction. Add a little oil and turmeric when blending to preserve the color.', 'I freeze mine in ice cube trays and just pop a cube into the pan when cooking.', 'A pinch of salt acts as a preservative. Keep it in an airtight glass jar, not plastic.'] },
    { title: 'Getting the right consistency for Palak Paneer', content: 'My palak puree always separates from the water. How to fix?', replies: ['Blanch the spinach for exactly 2 minutes, then immediately shock it in ice water. This keeps the bright green color.', 'Add a spoonful of maize flour (makki ka atta) or heavy cream to bind the puree together.', 'Don\'t overcook the spinach after pureeing. Just simmer it for a few minutes.'] },
    { title: 'Cooking with Mustard Oil', content: 'A recipe calls for mustard oil. Can I use olive oil instead?', replies: ['Mustard oil has a very distinct, pungent flavor crucial for Bengali and Bihari dishes. Olive oil will change the taste completely.', 'If you must substitute, use a neutral oil. Olive oil flavor clashes with Indian spices.', 'Remember to heat mustard oil to smoking point first, then cool it slightly before adding spices to remove the raw bite.'] },
    { title: 'Making perfect Basmati Rice on the stove', content: 'It always turns out sticky. What is the ratio?', replies: ['Wash the rice until the water runs clear. Soak for 30 mins. Use a 1:1.5 ratio of rice to water.', 'Bring to a boil, then cover with a tight lid and simmer on the lowest heat for 15 minutes. DO NOT open the lid.', 'Add a few drops of lemon juice or a teaspoon of ghee while boiling to keep the grains separate.'] },
    { title: 'Substitute for Tamarind paste', content: 'I don\'t have tamarind. What can I use for that sour tang?', replies: ['A mix of lime juice and a tiny bit of brown sugar can replicate the sweet and sour profile.', 'Amchur (dry mango powder) is a great substitute for tartness in dry dishes.', 'Kokum works well if you are cooking coastal Indian food.'] },
    { title: 'Keeping coriander leaves fresh', content: 'They wilt in my fridge within two days. Any tricks?', replies: ['Wash them, dry them completely in a salad spinner, wrap in a paper towel, and store in an airtight container.', 'Place the stems in a glass of water like a bouquet, cover the leaves with a plastic bag, and keep in the fridge.', 'Chop them and freeze them in a ziplock bag. They won\'t be good for garnish, but fine for cooking.'] },
    { title: 'Making crispy onion pakoras (Kanda Bhaji)', content: 'Mine are always doughy inside. How to make them crispy?', replies: ['Slice the onions very thin. Don\'t add water; just use the moisture from the salted onions to bind the besan.', 'Add a tablespoon of rice flour to the besan for extra crispiness.', 'Fry them in small batches on medium heat. If the oil is too hot, they brown outside and stay raw inside.'] },
    { title: 'Best pressure cooker for Indian cooking', content: 'Hawkins, Prestige, or Instant Pot?', replies: ['Instant Pot is the most versatile and you don\'t have to count whistles. Set it and forget it.', 'Hawkins classic is unmatched for traditional cooking. The inner lid design is very safe.', 'Prestige stainless steel is great for daily use. Avoid the aluminum ones.'] },
    { title: 'How to make Restaurant Style Dal Fry', content: 'What is the secret tadka for Dal Fry?', replies: ['The double tadka! One while cooking the dal, and a final one with ghee, cumin, garlic, and Kashmiri red chili right before serving.', 'Use a mix of Toor dal and Masoor dal for the best texture.', 'A pinch of hing (asafoetida) in the hot ghee is absolutely essential.'] },
    { title: 'Making authentic Chai', content: 'What spices do you put in your daily masala chai?', replies: ['Freshly grated ginger and crushed green cardamom. That\'s all you need for daily tea.', 'In winter, I add a tiny piece of cinnamon and a clove for warmth.', 'Boil the water with the spices and tea leaves first, then add the milk and boil again for the best flavor.'] }
  ],
  'Real estate in USA': [
    { title: 'Refinancing a mortgage right now', content: 'Rates dropped to 6%. I am at 7.2%. Is it worth refinancing?', replies: ['Calculate the closing costs. If it takes you 3 years to break even and you plan to stay 5+ years, do it.', 'Ask your current lender for a loan modification first. Sometimes they lower the rate for a small fee without a full refi.', 'Rule of thumb: Only refi if you can drop your rate by at least 1%. Wait a bit longer.'] },
    { title: 'Buying a foreclosure property', content: 'Are REO or foreclosed homes a good deal for first time buyers?', replies: ['Usually no. They are sold "as-is" and often have hidden damage from angry previous owners.', 'It requires a lot of cash because traditional lenders won\'t finance homes that need major repairs.', 'Leave foreclosures to experienced flippers. It is too risky for a primary residence.'] },
    { title: 'What is Title Insurance?', content: 'Lender requires it, but do I need an owner\'s policy too?', replies: ['Yes! Lender\'s policy protects the bank. Owner\'s policy protects YOU if someone claims they own your land.', 'It is a one-time fee at closing and absolutely essential. Do not skip it.', 'It protects against forged deeds, undisclosed heirs, and contractor liens. Worth every penny.'] },
    { title: 'Adjustable Rate Mortgage (ARM) vs Fixed', content: 'Lender is pushing a 5/1 ARM at 5.5%. Seems better than a 30-year fixed at 6.5%.', replies: ['ARMs are risky. If rates go up in 5 years, your payment will skyrocket. Only do it if you plan to sell or refi before 5 years.', 'It is a gamble. Historically, 30-year fixed provides the most stability and peace of mind.', 'Make sure you understand the "caps" (how much the rate can increase per year and over the life of the loan).'] },
    { title: 'Waiving contingencies to win a bid', content: 'Market is hot again. Should I waive the inspection contingency?', replies: ['Never waive the inspection completely. You can waive the *repair* contingency, meaning you won\'t ask for fixes, but you can still walk away if the house is falling apart.', 'Waiving appraisal is common, but you must have the cash to cover the gap.', 'It is a huge financial risk. Only waive if you have deep pockets for unexpected repairs.'] },
    { title: 'Is a Home Warranty worth it?', content: 'Seller is offering a 1-year home warranty. Are they useful?', replies: ['They are notoriously difficult to work with. They will try to patch a 20-year-old AC instead of replacing it.', 'If it is free from the seller, take it. But don\'t pay $600 out of your own pocket for a renewal.', 'It is better to put that $50/month into an emergency fund for repairs.'] },
    { title: 'Buying near a major highway', content: 'Found a great house, but it backs up to a busy interstate. Pros/cons?', replies: ['Con: Noise, dust, and lower resale value. Pro: Usually cheaper to buy.', 'Don\'t do it. The constant drone of tires will drive you crazy when you sit in the backyard.', 'Consider the air quality too, especially if you have kids. Exhaust fumes are a real issue.'] },
    { title: 'What are MUD taxes in Texas?', content: 'Looking at new builds in TX and see MUD/PID taxes. What are they?', replies: ['Municipal Utility Districts. They are extra taxes to pay for the infrastructure (water, roads) in new developments.', 'They can add thousands to your tax bill. Make sure you calculate the total tax rate, which can be over 3%.', 'They usually get paid off after 20-30 years, but you will likely sell the house before then.'] },
    { title: 'Renting out a single room in my house', content: 'Does anyone rent out a spare bedroom to a student? How is the experience?', replies: ['It is a great way to house hack. Just make sure to do a thorough background check and have a solid lease agreement.', 'It affects your privacy significantly. You are sharing your kitchen and living space.', 'Make sure you understand your local zoning laws; some HOAs prohibit renting out single rooms.'] },
    { title: 'Selling a house - Redfin vs Traditional Agent', content: 'Is the 1% listing fee from Redfin worth the reduced service?', replies: ['In a seller\'s market, yes. The house sells itself. You just need it on the MLS.', 'Traditional agents offer better marketing, staging advice, and negotiation skills, which can net you a higher sale price.', 'If your house needs work or is unique, use a traditional agent. If it is a cookie-cutter home in good condition, Redfin is fine.'] },
    { title: 'Buying a condo vs townhouse', content: 'What is the main difference for a first time buyer?', replies: ['With a condo, you only own the "airspace" inside the walls. Townhouse, you usually own the land underneath it too.', 'Condo HOAs are generally higher because they cover the master insurance policy for the entire building.', 'Townhouses appreciate better than condos and offer more privacy (no one living above or below you).'] },
    { title: 'How to check neighborhood safety', content: 'Moving to a new city. How do I verify if a neighborhood is safe?', replies: ['Drive through the area at 10 PM on a Friday night. That will tell you everything you need to know.', 'Check online crime maps (CrimeMapping or local police department data), but take them with a grain of salt.', 'Talk to the neighbors! Walk the street and ask people walking their dogs how they like the area.'] },
    { title: 'Impact of school ratings on property value', content: 'I don\'t have kids. Should I still care about the school district?', replies: ['Absolutely. Good school districts insulate home values during market downturns.', 'Houses in top-rated school districts appreciate faster and are much easier to sell later.', 'You will pay higher property taxes, but it is worth it for the resale value and neighborhood stability.'] },
    { title: 'What is Earnest Money?', content: 'Realtor says I need to put down $10k earnest money with my offer. Is this normal?', replies: ['Yes, it shows the seller you are serious. It goes toward your down payment at closing.', 'You get it back if you back out due to a contingency (like inspection or financing).', 'If you walk away for no valid reason, the seller keeps the earnest money as compensation.'] },
    { title: 'Buying a house with a pool', content: 'Is maintaining a pool a nightmare in the US?', replies: ['It costs about $150-$200/month for a pool service, plus extra electricity for the pump and chemicals.', 'It is great if you live in FL or AZ and use it 9 months a year. In the Northeast, it is a money pit.', 'When selling, a pool can actually deter some buyers who don\'t want the liability or maintenance.'] },
    { title: 'Should I get a Radon test?', content: 'House has a basement. Inspector recommends a radon test for $150.', replies: ['100% yes. Radon is the second leading cause of lung cancer. It is very common in certain regions.', 'Do it. If levels are high, you can negotiate with the seller to install a mitigation system ($1500).', 'Always test for radon if the house has a basement or crawlspace where you will spend time.'] },
    { title: 'Using an LLC to buy real estate', content: 'Should I buy my primary residence under an LLC for privacy?', replies: ['No, you lose the capital gains tax exemption ($250k/$500k) if you sell a primary residence owned by an LLC.', 'Mortgage rates are much higher for LLCs than for individuals.', 'LLCs are for investment properties to protect your personal assets from liability, not for your primary home.'] },
    { title: 'Dealing with a bidding war', content: 'Keep losing offers. How do I win without overpaying?', replies: ['Write a personal letter to the seller. Sometimes an emotional connection beats a slightly higher offer.', 'Offer a fast closing (21 days) or allow the seller a free leaseback for a month if they need time to move.', 'Have your lender call the listing agent to assure them your financing is rock solid.'] },
    { title: 'What is a Buyer\'s Agent Agreement?', content: 'Realtor wants me to sign an exclusive agreement before showing houses.', replies: ['This is standard now due to the recent NAR settlement. It ensures they get paid.', 'Make sure you understand their fee. If the seller doesn\'t offer enough commission, YOU might have to pay the difference.', 'Only sign it for a short period (like 30 days) or specific houses until you trust the agent.'] },
    { title: 'Pros and cons of corner lots', content: 'Found a house on a corner lot. Is it better than an interior lot?', replies: ['Pros: More light, only one adjacent neighbor, usually a bigger yard. Cons: More sidewalk to shovel/mow, less privacy, more street noise.', 'Corner lots are a target for cars cutting the corner or people walking across your lawn.', 'If there is a stop sign on your corner, be prepared for constant braking and accelerating noise.'] }
  ],
  'New to USA': [
    { title: 'How does US healthcare work if I lose my job?', content: 'If I get laid off on H1B, do I lose my health insurance immediately?', replies: ['You can use COBRA to keep your employer\'s insurance, but you have to pay the full premium (often $600-$1000/month).', 'Your insurance usually lasts until the end of the month in which you were terminated.', 'You can also buy a short-term plan on the ACA marketplace since losing your job is a qualifying life event.'] },
    { title: 'Best credit card for grocery shopping', content: 'Which card gives the best cash back for supermarkets?', replies: ['Amex Blue Cash Preferred gives 6% back on groceries up to $6000/year. It has a $95 annual fee but pays for itself.', 'Citi Custom Cash gives 5% back on your top spending category each billing cycle.', 'Capital One SavorOne gives 3% back on groceries and dining with no annual fee.'] },
    { title: 'Understanding US credit scores (FICO)', content: 'Why did my score drop 20 points when I paid off my car loan?', replies: ['Paying off an installment loan closes the account, which can lower your average age of accounts and change your credit mix. It is normal.', 'Your score will bounce back in a few months. Don\'t stress over small fluctuations.', 'Keep your credit card utilization below 10% for the best possible score.'] },
    { title: 'What is a HSA (Health Savings Account)?', content: 'HR is pushing a High Deductible plan with an HSA. Is it a good idea?', replies: ['An HSA is the ultimate tax hack. Contributions are tax-deductible, growth is tax-free, and withdrawals for medical expenses are tax-free.', 'If you are young and rarely go to the doctor, an HDHP + HSA is the smartest financial move.', 'You can invest the money in the HSA just like a 401k. Treat it as a retirement account for future medical costs.'] },
    { title: 'Buying furniture for first apartment', content: 'IKEA, Amazon, or Wayfair? Looking for budget but decent quality.', replies: ['IKEA is the best for budget. Wayfair quality is very hit or miss. Amazon is okay for small things.', 'Check Facebook Marketplace! You can find high-quality, solid wood furniture from West Elm or Pottery Barn for the price of IKEA.', 'Don\'t buy everything at once. Buy a mattress and a couch first, then slowly furnish the rest.'] },
    { title: 'How to deal with US winters', content: 'Moving to the Northeast. What is a "Snow Emergency"?', replies: ['A snow emergency means you must move your car off the street so plows can get through, or you will be towed.', 'Invest in a good snow shovel and ice melt BEFORE the first storm hits. Stores run out fast.', 'Get winter tires if you plan to drive a lot. All-season tires are not great in heavy snow.'] },
    { title: 'Understanding US taxes - W4 form', content: 'Starting a new job. How many allowances should I claim on the W-4?', replies: ['The new W-4 form (since 2020) no longer uses allowances. You just enter your filing status and dependents.', 'Use the IRS Tax Withholding Estimator online to figure out exactly how to fill it out.', 'If you are single with one job, just check "Single" and sign it. The default withholding is usually accurate.'] },
    { title: 'Is it safe to drink tap water?', content: 'Can I drink straight from the tap, or do I need a Brita filter?', replies: ['In 99% of US cities, tap water is perfectly safe to drink. A Brita filter just improves the taste by removing chlorine.', 'Check your local municipality\'s annual water quality report online.', 'If you live in a very old building, you might want to test for lead, but otherwise, tap water is highly regulated.'] },
    { title: 'Renting a car in the US', content: 'Do I need an International Driving Permit (IDP) to rent a car?', replies: ['Most rental companies (Enterprise, Hertz) will accept your Indian driving license if it is in English.', 'It is highly recommended to get an IDP anyway. Some strict police officers might demand it if you are pulled over.', 'Make sure you have a credit card; rental companies often reject debit cards or require huge deposits for them.'] },
    { title: 'Understanding US tipping - Hotels and Taxis', content: 'Do I tip hotel housekeeping and Uber drivers?', replies: ['Housekeeping: $2-$5 per day left on the pillow is a nice gesture, especially for longer stays. Uber: 10-20% depending on the service.', 'Bellhops usually get $1-$2 per bag. Valet parking is $2-$5 when they bring your car.', 'Tipping is getting out of hand, but these service workers rely heavily on it.'] },
    { title: 'Best way to build credit history fast', content: 'I got a secured card. How long until I get a decent score?', replies: ['It takes about 6 months of on-time payments to generate your first FICO score.', 'Always pay the statement balance in full every month. Do not carry a balance; you don\'t need to pay interest to build credit.', 'Ask a friend or family member with good credit to add you as an "Authorized User" on their old credit card. It boosts your score instantly.'] },
    { title: 'Navigating US grocery stores', content: 'What is the difference between Half & Half, Heavy Cream, and Whipping Cream?', replies: ['Half & Half is half milk, half cream (10-12% fat). Heavy Cream is thick (36%+ fat). Whipping Cream is slightly lighter (30% fat).', 'For Indian gravies, use Heavy Cream for richness. Half & Half works but is less creamy.', 'Use Half & Half in your morning coffee!'] },
    { title: 'Dealing with spam calls', content: 'I keep getting calls about my car\'s extended warranty. How to stop them?', replies: ['Register your number on the National Do Not Call Registry. It helps a little.', 'Don\'t answer calls from unknown numbers. If it\'s important, they will leave a voicemail.', 'Most modern smartphones have a "Silence Unknown Callers" feature. Turn it on.'] },
    { title: 'Understanding US apartment leases', content: 'What happens if I break my lease early?', replies: ['Read your lease! Usually, there is a penalty of 1-2 months\' rent to break it.', 'In some states, the landlord is required to "mitigate damages" by trying to find a new tenant quickly, which can lower your penalty.', 'You can often try to find someone to sublet or take over your lease (lease transfer) to avoid fees.'] },
    { title: 'Best internet service providers', content: 'Comcast/Xfinity vs AT&T Fiber. Which is better?', replies: ['Fiber is ALWAYS better than cable. If AT&T Fiber is available, get it. Symmetrical upload/download speeds and lower latency.', 'Comcast is notorious for terrible customer service and random price hikes.', 'Buy your own modem and router instead of renting theirs for $15/month. It pays for itself in a year.'] },
    { title: 'How to dispose of large items', content: 'How do I throw away an old mattress or broken TV?', replies: ['Do not just throw it in the apartment dumpster; you will be fined. Check your city\'s "Bulk Trash Pickup" schedule.', 'You can take it to the local county dump/landfill for a small fee.', 'Electronics (TVs) must be recycled. Best Buy often takes old electronics for free.'] },
    { title: 'Understanding "At-Will" employment', content: 'My offer letter says employment is "at-will". Is this normal?', replies: ['Yes, 49 out of 50 US states are "at-will". It means they can fire you at any time for any legal reason, and you can quit at any time.', 'It offers zero job security. This is why having an emergency fund is critical in the US.', 'Only union workers and some executives with specific contracts are exempt from at-will employment.'] },
    { title: 'Finding an Indian grocery store', content: 'Moving to a small town. What if there is no Patel Brothers nearby?', replies: ['Look for generic "Asian Markets" or Middle Eastern stores. They often carry spices, rice, and lentils.', 'Order online! Weee! app is amazing for Asian groceries, and Amazon has plenty of Indian staples.', 'Stock up heavily when you visit a larger city once a month. Freeze things like paneer and fresh veggies.'] },
    { title: 'What is a Credit Union?', content: 'Are they better than big banks like Chase or Bank of America?', replies: ['Credit unions are non-profit, owned by their members. They usually offer much lower loan rates and higher interest on savings.', 'The customer service is usually much better, but they have fewer branches and less robust apps than big banks.', 'Always use a credit union for auto loans. Their rates beat dealership financing 90% of the time.'] },
    { title: 'Navigating small talk - "How are you?"', content: 'People ask "How are you?" but keep walking. Are they expecting an answer?', replies: ['In the US, "How are you?" is just a greeting, like saying "Hello". They don\'t actually want to know how you are.', 'Just reply "Good, how are you?" and keep walking. It is a cultural quirk.', 'Only give a real answer if you are having a sit-down conversation with a friend or close colleague.'] }
  ],
  'About Studies': [
    { title: 'Is a Master\'s degree worth it in 2026?', content: 'With AI coding assistants getting better, is an MS in CS still a good investment?', replies: ['An MS is primarily an entry ticket to the US job market. The degree itself is just a checkbox.', 'AI will augment engineers, not replace senior ones. Focus on system design and architecture during your MS.', 'If you have to take a huge loan at 12% interest, it is becoming a much riskier proposition than it was 5 years ago.'] },
    { title: 'Co-op vs Summer Internship', content: 'My university offers a 6-month Co-op. Should I do that instead of a 3-month summer internship?', replies: ['Absolutely! A 6-month Co-op gives you real project experience and a much higher chance of a return offer.', 'Be careful, doing a 6-month Co-op might consume your entire 1-year CPT allowance, meaning no more internships.', 'It might delay your graduation by a semester, but entering the market with 6 months of US experience is a massive advantage.'] },
    { title: 'How to approach professors for RA/TA', content: 'Should I email them before the semester starts or visit their office?', replies: ['Email them a month before, attaching your resume and a specific mention of a paper they recently published.', 'Cold emails rarely work. Do well in their class for a few weeks, then go to office hours and ask in person.', 'Talk to current PhD students in their lab. If the PhDs like you, they will recommend you to the professor.'] },
    { title: 'Difference between Thesis and Non-Thesis MS', content: 'Which track is better for industry jobs?', replies: ['For industry, 100% go for the Non-Thesis (coursework/project) option. It is faster and lets you focus on Leetcode and internships.', 'Only do the Thesis track if you are planning to apply for a PhD later or want to work in a heavy R&D role.', 'Thesis takes up a lot of time and depends heavily on your advisor. Avoid it if your goal is just to become a SWE.'] },
    { title: 'What is a good GRE score now?', content: 'Are universities still caring about GRE scores post-COVID?', replies: ['Many top universities have made the GRE optional or dropped it entirely. Check individual program requirements.', 'If you have a low undergraduate GPA, a high GRE score (325+) can help offset it.', 'Focus more on your Statement of Purpose (SOP) and Letters of Recommendation. They matter much more now.'] },
    { title: 'Surviving the first winter in the US', content: 'Moving to a university in upstate NY. How bad is the snow?', replies: ['It is brutal. Buy a heavy down parka, waterproof boots, and thermal layers. Do not skimp on winter gear.', 'Seasonal Affective Disorder (SAD) is real. Get a Vitamin D supplement and a happy light for your room.', 'The university is usually well-equipped to clear paths, but give yourself extra time to walk to class.'] },
    { title: 'Understanding Plagiarism rules in the US', content: 'Is it okay to use ChatGPT to help write assignments?', replies: ['Most universities have strictly banned the use of AI for writing essays or generating code unless explicitly allowed by the professor.', 'They use sophisticated AI detectors now. It is considered an academic integrity violation.', 'Use it as a tutor to understand concepts, but do NOT copy-paste anything from it into your assignments.'] },
    { title: 'Best banks for international students', content: 'Which bank is easiest to open an account with on an F1 visa?', replies: ['Chase is very student-friendly and usually offers a $200 bonus for opening a student checking account.', 'Bank of America is also very common on campuses and doesn\'t require an SSN to open a basic account.', 'Avoid online-only banks initially; you often need an SSN and US credit history to open those.'] },
    { title: 'Dealing with group projects', content: 'My group members are slacking off. How do I handle this?', replies: ['Document everything. Keep all communication in a group chat. If they don\'t contribute, talk to the professor early, not the night before it\'s due.', 'Take the lead, assign specific tasks with hard deadlines, and hold them accountable.', 'Unfortunately, carrying a group project is a common experience. Protect your own grade above all.'] },
    { title: 'How to write a strong Statement of Purpose (SOP)', content: 'Should I talk about my childhood dreams of coding?', replies: ['No! Admissions committees hate the "Ever since I was a child playing video games..." cliché.', 'Focus on your professional goals, what specific research/classes at THEIR university align with your goals, and what you bring to the table.', 'Keep it concise, professional, and heavily tailored to the specific university you are applying to.'] },
    { title: 'What is a WES evaluation?', content: 'Do I really need to pay $200 for this credential evaluation?', replies: ['Only do it if the specific university strictly requires it. Many universities do their own internal evaluation of Indian transcripts.', 'If your university uses a non-4.0 grading scale, WES converts it to the US standard, which can sometimes boost your perceived GPA.', 'Check the admissions FAQ carefully. Don\'t waste money if it\'s optional.'] },
    { title: 'Attending Career Fairs as a first-year student', content: 'Is it worth going to the career fair in my first month?', replies: ['Yes, go just to practice your elevator pitch and get used to the chaotic environment. Expect nothing, gain experience.', 'It helps you understand what skills companies are actively looking for so you can tailor your electives.', 'Sometimes you can score a co-op or a connection for next year. Grab the free swag too!'] },
    { title: 'Should I buy a car as a student?', content: 'My campus is spread out. Is buying a cheap $5k car worth it?', replies: ['A $5k car will likely cost you another $3k in repairs in the first year. Plus insurance for a new international driver is insanely expensive.', 'Try to live near a campus shuttle route or buy a good electric scooter/bike instead.', 'Only buy a car if you live in a city with absolutely zero public transit and you cannot walk to groceries.'] },
    { title: 'How to manage stress and anxiety', content: 'The coursework pressure is getting to me. Does the university offer help?', replies: ['Yes, every university has a Counseling and Psychological Services (CAPS) center. It is free for students. Use it!', 'Don\'t isolate yourself. Talk to your seniors; they went through the exact same shock and survived.', 'Make sure you are sleeping 7 hours and eating well. Burnout is the biggest threat to your grades.'] },
    { title: 'What is OPT Premium Processing?', content: 'USCIS introduced premium processing for OPT. Is the $1500 worth it?', replies: ['Only if you have a job offer starting very soon and your standard OPT application has been pending for over 60 days.', 'Standard processing usually takes 3-4 weeks right now. Don\'t waste $1500 unless it is an absolute emergency.', 'If your employer is willing to reimburse the cost, go for it!'] },
    { title: 'Applying for SSN Delay', content: 'I got an on-campus job but the SSN office says my SEVIS isn\'t active yet.', replies: ['Your DSO needs to activate your SEVIS record in the system. This usually happens 1-2 weeks after classes start.', 'You can legally start working on campus while your SSN application is pending, as long as HR has your receipt.', 'Follow up with your International Students Office. They hold the keys to SEVIS.'] },
    { title: 'Best phone carrier for students', content: 'Are the family plans on WhatsApp groups safe to join?', replies: ['Joining a family plan with strangers is risky. If the account owner stops paying, your number gets disconnected.', 'Get Mint Mobile or Visible. They are cheap ($15-$25/mo) and you control your own account.', 'If you have 3-4 trusted friends, start your own family plan on T-Mobile or AT&T.'] },
    { title: 'Working off-campus illegally', content: 'A local restaurant is offering cash in hand. Is it worth the risk?', replies: ['NO! It is a direct violation of your F1 visa. If caught, you will be deported and banned from the US.', 'It is not worth risking your entire career and the thousands of dollars you spent on tuition for a few bucks.', 'Find an on-campus job. It is legal and builds your resume safely.'] },
    { title: 'How to get in-state tuition', content: 'I am an international student. Is there any way to get the cheaper in-state tuition rate?', replies: ['In states like Texas, getting a competitive university scholarship of at least $1000 often grants you a waiver for out-of-state tuition.', 'Being a TA/RA usually comes with a full or partial tuition waiver, lowering your costs to in-state levels or zero.', 'Otherwise, international students almost always pay the full out-of-state premium.'] },
    { title: 'Should I stay in the US for summer or go to India?', content: 'No internship lined up. Should I just visit home?', replies: ['Stay and take summer classes to graduate early, or work on a major personal project to boost your resume for fall recruiting.', 'Going home for 3 months looks like a gap on your resume. Use the time productively.', 'If you are severely burnt out, a 3-week trip home is fine, but spend the rest of the summer upskilling.'] }
  ],
  'Kids': [
    { title: 'Navigating peanut allergies in schools', content: 'My kindergartener has a severe peanut allergy. How do US schools handle this?', replies: ['Most elementary schools have designated "peanut-free" tables in the cafeteria. Make sure to get an allergy action plan from your pediatrician on file with the school nurse.', 'Talk to the teacher before the school year starts. They will usually enforce a strict no-nut snack policy in the classroom.', 'Always provide your own safe cupcakes for classroom birthday parties so your child isn\'t left out.'] },
    { title: 'Are travel sports worth the cost and time?', content: 'My 9-year-old wants to join a travel soccer team. It costs $3000 and kills weekends.', replies: ['Only do it if your child is extremely passionate and has genuine talent. The pressure and time commitment are immense.', 'It ruins family weekends. Recreational leagues are perfectly fine for keeping kids active and teaching teamwork.', 'Unless you are banking on a D1 college scholarship (which is rare), the ROI on travel sports is terrible.'] },
    { title: 'Best age for sleepovers', content: 'At what age did you allow your kids to sleep over at a friend\'s house?', replies: ['We started around age 8, but only with families we knew extremely well and whose parenting styles we trusted.', 'We prefer "late-overs" where they stay until 10 PM, watch a movie, and then we pick them up. Less anxiety for everyone.', 'Never be afraid to ask the parents about gun ownership and how they are stored before allowing a sleepover.'] },
    { title: 'Teaching kids about money in a cashless society', content: 'How do you teach the value of a dollar when they only see credit cards?', replies: ['We use the Greenlight app. It gives them a debit card and we can set chores and interest rates. They learn fast when it\'s "their" digital money.', 'Give them physical cash for their allowance until they are at least 10. The physical act of handing over money hurts more than a card swipe.', 'Take them to the grocery store and have them calculate the cost of their favorite snacks vs generic brands.'] },
    { title: 'Coping with daylight saving time changes', content: 'Spring forward always ruins my toddler\'s sleep schedule for weeks. Tips?', replies: ['Start shifting their bedtime 15 minutes earlier every night for four days leading up to the time change.', 'Invest in good blackout curtains. The extra hour of sunlight in the evening makes it hard for them to wind down.', 'Be patient. It takes about a week for their circadian rhythm to adjust. Stick strictly to the routine.'] },
    { title: 'Should we force kids to learn a musical instrument?', content: 'I want my son to learn piano, but he hates practicing.', replies: ['Don\'t force it. It will make them hate music. Let them try different instruments or activities until they find what *they* like.', 'We made a deal: you have to stick with an instrument for one full year. If you still hate it after that, you can quit.', 'Music education is great for brain development, but forcing practice turns it into a chore, defeating the purpose.'] },
    { title: 'Navigating the "Birds and the Bees" talk', content: 'When and how did you approach this topic? My 7-year-old is asking questions.', replies: ['Answer exactly what they ask, simply and scientifically, without giving too much extra detail. Use proper anatomical terms.', 'There is a great book called "It\'s Perfectly Normal" that is very age-appropriate and helpful.', 'Don\'t make it one big awkward talk. Make it a series of small, open conversations as they grow.'] },
    { title: 'Is a trampoline in the backyard a bad idea?', content: 'The kids are begging for one, but I am worried about injuries.', replies: ['As a pediatrician: do not get one. The number of fractures and concussions we see from backyard trampolines is staggering.', 'If you do get one, enforce a strict "one at a time" rule and make sure it has a high-quality safety net.', 'Your home insurance premium might go up, or they might even drop you. Check your policy first.'] },
    { title: 'How to deal with a picky eater', content: 'My 4-year-old only eats plain pasta and chicken nuggets. Help!', replies: ['Remember the division of responsibility: You decide *what* to serve and *when*. They decide *whether* to eat and *how much*. Don\'t become a short-order cook.', 'Keep offering new foods alongside their safe foods without any pressure to try them. It takes 15+ exposures for a kid to accept a new food.', 'Involve them in cooking. Kids are much more likely to eat something they helped make.'] },
    { title: 'Finding diverse books for Indian-American kids', content: 'I want my kids to see themselves in stories. Recommendations?', replies: ['Look into "Bharat Babies" or "Mango & Marigold Press". They publish beautiful books featuring South Asian characters.', 'The "Priya Dreams of Marigolds & Masala" and "Bindu\'s Bindis" are wonderful picture books.', 'Check your local library! Many librarians have curated lists of diverse children\'s literature.'] },
    { title: 'When to stop using a stroller', content: 'My 4-year-old refuses to walk long distances (like at the zoo). Is he too old for a stroller?', replies: ['For an all-day event like a theme park or zoo, a stroller or a wagon is totally fine for a 4-year-old. Saves everyone\'s sanity.', 'Start building their stamina on shorter walks around the neighborhood without the stroller.', 'A folding wagon is a great transition. They can hop in when tired, but it feels less like a "baby" stroller.'] },
    { title: 'Are smartwatches for kids safe?', content: 'Thinking of getting a Gizmo watch for my 9-year-old to track them. Good idea?', replies: ['They are fantastic for peace of mind. You can track their location and they can only call/text approved numbers.', 'It is a great stepping stone before a full smartphone. It teaches responsibility without the dangers of the internet.', 'Just make sure the school allows them. Many schools require them to be kept in backpacks during class hours.'] },
    { title: 'Handling grandparent interference', content: 'My in-laws spoil the kids and ignore our rules when they visit. How to handle?', replies: ['Your spouse needs to be the one to set boundaries with their own parents. It should come from them, not you.', 'Pick your battles. Let them be spoiled for a weekend visit. If they live with you, that is a different story and requires strict rules.', 'Present a united front. "Mom and Dad decided that bedtime is 8 PM, no exceptions."'] },
    { title: 'Best family vacation spots in the US', content: 'Looking for ideas for a 1-week trip with a 5 and 8-year-old. Not Disney.', replies: ['The National Parks! Yellowstone or Yosemite are magical for kids. Do the Junior Ranger programs.', 'San Diego is incredibly family-friendly. Great weather, beaches, the Zoo, and Legoland.', 'Washington D.C. is fantastic because all the Smithsonian museums and the Zoo are completely free.'] },
    { title: 'When do kids lose their accents?', content: 'We moved from India last year. My 6-year-old still has a strong accent. Will he get bullied?', replies: ['At 6 years old, they will absorb the local accent within 6 to 12 months. It happens incredibly fast.', 'Kids are adaptable. Don\'t stress about the accent; worry more about building their confidence.', 'They might end up with two accents! One they use at school with friends, and one they use at home with you.'] },
    { title: 'Is a gap year before college a good idea?', content: 'My high school senior is burnt out and wants to travel for a year.', replies: ['If they have a structured plan (volunteering, working, or a structured travel program), it can be incredibly maturing and beneficial.', 'Have them apply to college now, get accepted, and then request a deferral for a year. That way their spot is secure.', 'A gap year spent playing video games in the basement is a bad idea. Structure is crucial.'] },
    { title: 'Dealing with childhood anxiety', content: 'My 10-year-old is having panic attacks about school tests. Advice?', replies: ['Please consult a pediatric therapist. Cognitive Behavioral Therapy (CBT) works wonders for childhood anxiety.', 'Don\'t put pressure on grades. Emphasize that you care about their effort, not the final letter grade.', 'Teach them grounding techniques, like the 5-4-3-2-1 method, to use when they feel a panic attack coming on.'] },
    { title: 'When to let kids stay home alone', content: 'What is the legal age, and how do you know they are ready?', replies: ['Most states don\'t have a strict legal age, but guidelines usually suggest 11 or 12 for short periods. Check your state laws.', 'Start small. Leave them for 15 minutes while you run to the gas station. See how they handle it.', 'Make sure they know what to do in an emergency, how to lock doors, and not to answer the door for anyone.'] },
    { title: 'Best practices for kids sharing a room', content: 'Moving to a smaller place. My 5-year-old and 8-year-old have to share.', replies: ['Create distinct "zones" for each kid, even if it is just different colored rugs or bookshelves. They need their own space.', 'Use a white noise machine. It prevents one kid waking up the other if they toss and turn.', 'Establish a strict "quiet time" rule for the older one if the younger one goes to bed earlier.'] },
    { title: 'Is Montessori worth the hype?', content: 'Looking at preschools. Montessori is twice the price of regular daycares.', replies: ['True Montessori fosters incredible independence and focus. It is great, but only if the school is actually accredited (AMI or AMS).', 'A lot of schools just slap the word "Montessori" on their name to charge more. Do your research.', 'Play-based preschools are just as good for social-emotional development, which is the most important thing at that age.'] }
  ]
};

let phpCode = \`<?php

namespace Database\\\\Seeders;

use Illuminate\\\\Database\\\\Seeder;
use App\\\\Models\\\\User;
use App\\\\Models\\\\ForumPost;
use App\\\\Models\\\\ForumComment;
use Illuminate\\\\Support\\\\Facades\\\\Hash;

class ForumSeeder extends Seeder
{
    public function run(): void
    {
        $userData = [
            ["Aarav Sharma", "aarav123@sharklasers.com"], ["Vivaan Patel", "vivaan123@sharklasers.com"],
            ["Aditya Singh", "aditya123@sharklasers.com"], ["Arjun Gupta", "arjun123@sharklasers.com"],
            ["Sai Reddy", "sai123@sharklasers.com"], ["Krishna Nair", "krishna123@sharklasers.com"],
            ["Rahul Mehta", "rahul123@sharklasers.com"], ["Karthik Iyer", "karthik123@sharklasers.com"],
            ["Rohan Das", "rohan123@sharklasers.com"], ["Mohan Pillai", "mohan123@sharklasers.com"],
            ["Ananya Sharma", "ananya123@sharklasers.com"], ["Diya Patel", "diya123@sharklasers.com"],
            ["Isha Singh", "isha123@sharklasers.com"], ["Kavya Gupta", "kavya123@sharklasers.com"],
            ["Sneha Reddy", "sneha123@sharklasers.com"], ["Meera Nair", "meera123@sharklasers.com"],
            ["Pooja Mehta", "pooja123@sharklasers.com"], ["Aishwarya Iyer", "aishwarya123@sharklasers.com"],
            ["Neha Das", "neha123@sharklasers.com"], ["Lakshmi Pillai", "lakshmi123@sharklasers.com"],
            ["Varun Sharma", "varun123@sharklasers.com"], ["Nikhil Patel", "nikhil123@sharklasers.com"],
            ["Suresh Singh", "suresh123@sharklasers.com"], ["Rajesh Gupta", "rajesh123@sharklasers.com"],
            ["Ajay Reddy", "ajay123@sharklasers.com"], ["Manoj Nair", "manoj123@sharklasers.com"],
            ["Deepak Mehta", "deepak123@sharklasers.com"], ["Sanjay Iyer", "sanjay123@sharklasers.com"],
            ["Vijay Das", "vijay123@sharklasers.com"], ["Prakash Pillai", "prakash123@sharklasers.com"],
            ["Priya Sharma", "priya123@sharklasers.com"], ["Ritu Patel", "ritu123@sharklasers.com"],
            ["Swati Singh", "swati123@sharklasers.com"], ["Nisha Gupta", "nisha123@sharklasers.com"],
            ["Komal Reddy", "komal123@sharklasers.com"], ["Rekha Nair", "rekha123@sharklasers.com"],
            ["Shalini Mehta", "shalini123@sharklasers.com"], ["Divya Iyer", "divya123@sharklasers.com"],
            ["Poonam Das", "poonam123@sharklasers.com"], ["Radha Pillai", "radha123@sharklasers.com"],
            ["Akash Sharma", "akash123@sharklasers.com"], ["Imran Patel", "imran123@sharklasers.com"],
            ["Yusuf Singh", "yusuf123@sharklasers.com"], ["Sameer Gupta", "sameer123@sharklasers.com"],
            ["Farhan Reddy", "farhan123@sharklasers.com"], ["Zaid Nair", "zaid123@sharklasers.com"],
            ["Arif Mehta", "arif123@sharklasers.com"], ["Salman Iyer", "salman123@sharklasers.com"],
            ["Javed Das", "javed123@sharklasers.com"], ["Rizwan Pillai", "rizwan123@sharklasers.com"],
            ["Tanya Sharma", "tanya123@sharklasers.com"], ["Alia Patel", "alia123@sharklasers.com"],
            ["Sara Singh", "sara123@sharklasers.com"], ["Hina Gupta", "hina123@sharklasers.com"],
            ["Sana Reddy", "sana123@sharklasers.com"], ["Fatima Nair", "fatima123@sharklasers.com"],
            ["Zoya Mehta", "zoya123@sharklasers.com"], ["Amina Iyer", "amina123@sharklasers.com"],
            ["Nazia Das", "nazia123@sharklasers.com"], ["Shabana Pillai", "shabana123@sharklasers.com"],
            ["Dev Sharma", "dev123@sharklasers.com"], ["Harsh Patel", "harsh123@sharklasers.com"],
            ["Kunal Singh", "kunal123@sharklasers.com"], ["Tarun Gupta", "tarun123@sharklasers.com"],
            ["Gaurav Reddy", "gaurav123@sharklasers.com"], ["Lokesh Nair", "lokesh123@sharklasers.com"],
            ["Naveen Mehta", "naveen123@sharklasers.com"], ["Sandeep Iyer", "sandeep123@sharklasers.com"],
            ["Amit Das", "amit123@sharklasers.com"], ["Bharat Pillai", "bharat123@sharklasers.com"],
            ["Riya Sharma", "riya123@sharklasers.com"], ["Siya Patel", "siya123@sharklasers.com"],
            ["Anjali Singh", "anjali123@sharklasers.com"], ["Preeti Gupta", "preeti123@sharklasers.com"],
            ["Jyoti Reddy", "jyoti123@sharklasers.com"], ["Usha Nair", "usha123@sharklasers.com"],
            ["Lata Mehta", "lata123@sharklasers.com"], ["Bhavna Iyer", "bhavna123@sharklasers.com"],
            ["Kiran Das", "kiran123@sharklasers.com"], ["Sudha Pillai", "sudha123@sharklasers.com"],
            ["Om Sharma", "om123@sharklasers.com"], ["Tejas Patel", "tejas123@sharklasers.com"],
            ["Dhruv Singh", "dhruv123@sharklasers.com"], ["Yash Gupta", "yash123@sharklasers.com"],
            ["Ritesh Reddy", "ritesh123@sharklasers.com"], ["Vignesh Nair", "vignesh123@sharklasers.com"],
            ["Ashwin Mehta", "ashwin123@sharklasers.com"], ["Surya Iyer", "surya123@sharklasers.com"],
            ["Naveed Das", "naveed123@sharklasers.com"], ["Faizal Pillai", "faizal123@sharklasers.com"],
            ["Aarti Sharma", "aarti123@sharklasers.com"], ["Deepa Patel", "deepa123@sharklasers.com"],
            ["Monika Singh", "monika123@sharklasers.com"], ["Rachna Gupta", "rachna123@sharklasers.com"],
            ["Sushma Reddy", "sushma123@sharklasers.com"], ["Geeta Nair", "geeta123@sharklasers.com"],
            ["Hema Mehta", "hema123@sharklasers.com"], ["Revathi Iyer", "revathi123@sharklasers.com"],
            ["Sunita Das", "sunita123@sharklasers.com"], ["Malathi Pillai", "malathi123@sharklasers.com"]
        ];

        $users = [];
        foreach ($userData as $data) {
            $users[] = User::updateOrCreate(
                ['email' => $data[1]],
                [
                    'name' => $data[0],
                    'password' => Hash::make('password123'),
                ]
            );
        }

        // Keep existing ones! DO NOT DELETE
        // ForumComment::query()->delete();
        // ForumPost::query()->delete();

        $startDate = strtotime('2025-10-01');
        $endDate = strtotime('2026-04-30');

\`;

for (const [category, posts] of Object.entries(categories)) {
  for (const post of posts) {
    phpCode += \`
        $postDate = date('Y-m-d H:i:s', rand($startDate, $endDate));
        $post = ForumPost::create([
            'user_id' => $users[array_rand($users)]->id,
            'title' => '\${post.title.replace(/'/g, "\\\\'")}',
            'content' => '\${post.content.replace(/'/g, "\\\\'")}',
            'category' => '\${category}',
            'votes' => rand(10, 500),
            'created_at' => $postDate,
            'updated_at' => $postDate
        ]);
\`;
    for (const reply of post.replies) {
      phpCode += \`
        $commentDate = date('Y-m-d H:i:s', rand(strtotime($postDate), $endDate));
        ForumComment::create([
            'user_id' => $users[array_rand($users)]->id,
            'post_id' => $post->id,
            'content' => '\${reply.replace(/'/g, "\\\\'")}',
            'votes' => rand(0, 50),
            'created_at' => $commentDate,
            'updated_at' => $commentDate
        ]);
\`;
    }
  }
}

phpCode += \`
    }
}
\`;

fs.writeFileSync('f:/Desipath-code/desipath/BACKEND/database/seeders/ForumSeeder.php', phpCode);
console.log('ForumSeeder.php successfully generated with completely new and perfectly correlated replies.');
