<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AirportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('airports')->truncate();

        $airports = [
            ['iata_code' => 'BHM', 'airport_name' => 'Birmingham–Shuttlesworth Intl ', 'city' => 'Birmingham', 'region' => 'Alabama', 'country' => 'United States'],
            ['iata_code' => 'DHN', 'airport_name' => 'Dothan Regional ', 'city' => 'Dothan', 'region' => 'Alabama', 'country' => 'United States'],
            ['iata_code' => 'HSV', 'airport_name' => 'Huntsville Intl  (Carl T. Jones Field)', 'city' => 'Huntsville', 'region' => 'Alabama', 'country' => 'United States'],
            ['iata_code' => 'MOB', 'airport_name' => 'Mobile Regional ', 'city' => 'Mobile', 'region' => 'Alabama', 'country' => 'United States'],
            ['iata_code' => 'MGM', 'airport_name' => 'Montgomery Regional  Dannelly Field', 'city' => 'Montgomery', 'region' => 'Alabama', 'country' => 'United States'],
            ['iata_code' => 'MRI', 'airport_name' => 'Merrill Field', 'city' => 'Anchorage', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'ANC', 'airport_name' => 'Ted Stevens Anchorage Intl ', 'city' => 'Anchorage', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'BET', 'airport_name' => 'Bethel ', 'city' => 'Bethel', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'CDV', 'airport_name' => 'Merle K. (Mudhole) Smith ', 'city' => 'Cordova', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'SCC', 'airport_name' => 'Prudhoe Bay ', 'city' => 'Deadhorse', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'DLG', 'airport_name' => 'Dillingham ', 'city' => 'Dillingham', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'FAI', 'airport_name' => 'Fairbanks Intl ', 'city' => 'Fairbanks', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'GST', 'airport_name' => 'Gustavus ', 'city' => 'Gustavus', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'HOM', 'airport_name' => 'Homer ', 'city' => 'Homer', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'JNU', 'airport_name' => 'Juneau Intl ', 'city' => 'Juneau', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'ENA', 'airport_name' => 'Kenai Municipal ', 'city' => 'Kenai', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'KTN', 'airport_name' => 'Ketchikan Intl ', 'city' => 'Ketchikan', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'AKN', 'airport_name' => 'King Salmon ', 'city' => 'King Salmon', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'AKW', 'airport_name' => 'Klawock  ', 'city' => 'Klawock', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'ADQ', 'airport_name' => 'Kodiak  ', 'city' => 'Kodiak', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'OTZ', 'airport_name' => 'Ralph Wien Memorial ', 'city' => 'Kotzebue', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'OME', 'airport_name' => 'Nome ', 'city' => 'Nome', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'PSG', 'airport_name' => 'Petersburg James A. Johnson ', 'city' => 'Petersburg', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'SIT', 'airport_name' => 'Sitka Rocky Gutierrez ', 'city' => 'Sitka', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'DUT', 'airport_name' => 'Unalaska ', 'city' => 'Unalaska', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'BRW', 'airport_name' => 'Wiley Post–Will Rogers Memorial ', 'city' => 'Barrow', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'WRG', 'airport_name' => 'Wrangell  ', 'city' => 'Wrangell', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'YAK', 'airport_name' => 'Yakutat ', 'city' => 'Yakutat', 'region' => 'Alaska', 'country' => 'United States'],
            ['iata_code' => 'FLG', 'airport_name' => 'Flagstaff Pulliam ', 'city' => 'Flagstaff', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'PGA', 'airport_name' => 'Page Municipal ', 'city' => 'Page', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'PHX', 'airport_name' => 'Phoenix Sky Harbor Intl ', 'city' => 'Phoenix', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'PRC', 'airport_name' => 'Prescott Municipal Apt Ernest A. Love Field', 'city' => 'Prescott', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'TUS', 'airport_name' => 'Tucson Intl ', 'city' => 'Tucson', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'YUM', 'airport_name' => 'Yuma Intl  ', 'city' => 'Yuma', 'region' => 'Arizona', 'country' => 'United States'],
            ['iata_code' => 'XNA', 'airport_name' => 'Northwest Arkansas National ', 'city' => 'Fayetteville', 'region' => 'Arkansas', 'country' => 'United States'],
            ['iata_code' => 'FSM', 'airport_name' => 'Fort Smith Regional ', 'city' => 'Fort Smith', 'region' => 'Arkansas', 'country' => 'United States'],
            ['iata_code' => 'LIT', 'airport_name' => 'Clinton National  National', 'city' => 'Little Rock', 'region' => 'Arkansas', 'country' => 'United States'],
            ['iata_code' => 'TXK', 'airport_name' => 'Texarkana Regional  Webb Field', 'city' => 'Texarkana', 'region' => 'Arkansas', 'country' => 'United States'],
            ['iata_code' => 'ACV', 'airport_name' => 'California Redwood Coast–Humboldt County ', 'city' => 'Eureka', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'BFL', 'airport_name' => 'Meadows Field', 'city' => 'Bakersfield', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'BUR', 'airport_name' => 'Hollywood Burbank ', 'city' => 'Burbank', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'FAT', 'airport_name' => 'Fresno Yosemite Intl ', 'city' => 'Fresno', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'LGB', 'airport_name' => 'Long Beach  (Daugherty Field)', 'city' => 'Long Beach', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'LAX', 'airport_name' => 'Los Angeles Intl ', 'city' => 'Los Angeles', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'MRY', 'airport_name' => 'Monterey Regional ', 'city' => 'Monterey', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'OAK', 'airport_name' => 'Oakland Intl ', 'city' => 'Oakland', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'ONT', 'airport_name' => 'Ontario Intl ', 'city' => 'Ontario', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'PSP', 'airport_name' => 'Palm Springs Intl ', 'city' => 'Palm Springs', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'RDD', 'airport_name' => 'Redding Regional ', 'city' => 'Redding', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SMF', 'airport_name' => 'Sacramento Intl ', 'city' => 'Sacramento', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SAN', 'airport_name' => 'San Diego Intl ', 'city' => 'San Diego', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SFO', 'airport_name' => 'San Francisco Intl ', 'city' => 'San Francisco', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SJC', 'airport_name' => 'San Jose Intl ', 'city' => 'San Jose', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SBP', 'airport_name' => 'San Luis Obispo County Regional  ', 'city' => 'San Luis Obispo', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SNA', 'airport_name' => 'John Wayne ', 'city' => 'Santa Ana', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SBA', 'airport_name' => 'Santa Barbara Municipal  ', 'city' => 'Santa Barbara', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SMX', 'airport_name' => 'Santa Maria Public  ', 'city' => 'Santa Maria', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'STS', 'airport_name' => 'Charles M. Schulz–Sonoma County ', 'city' => 'Santa Rosa', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'SCK', 'airport_name' => 'Stockton Metropolitan ', 'city' => 'Stockton', 'region' => 'California', 'country' => 'United States'],
            ['iata_code' => 'ALS', 'airport_name' => 'San Luis Valley Regional  ', 'city' => 'Alamosa', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'ASE', 'airport_name' => 'Aspen/Pitkin County  ', 'city' => 'Aspen', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'COS', 'airport_name' => 'City of Colorado Springs Municipal ', 'city' => 'Colorado Springs', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'DEN', 'airport_name' => 'Denver Intl ', 'city' => 'Denver', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'DRO', 'airport_name' => 'Durango–La Plata County ', 'city' => 'Durango', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'EGE', 'airport_name' => 'Eagle County Regional ', 'city' => 'Eagle/Vail', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'GJT', 'airport_name' => 'Grand Junction Regional  ', 'city' => 'Grand Junction', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'GUC', 'airport_name' => 'Gunnison–Crested Butte Regional ', 'city' => 'Gunnison', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'HDN', 'airport_name' => 'Yampa Valley ', 'city' => 'Hayden', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'MTJ', 'airport_name' => 'Montrose Regional ', 'city' => 'Montrose', 'region' => 'Colorado', 'country' => 'United States'],
            ['iata_code' => 'BDL', 'airport_name' => 'Bradley Intl ', 'city' => 'Hartford', 'region' => 'Connecticut', 'country' => 'United States'],
            ['iata_code' => 'HVN', 'airport_name' => 'Tweed-New Haven ', 'city' => 'New Haven', 'region' => 'Connecticut', 'country' => 'United States'],
            ['iata_code' => 'ILG', 'airport_name' => 'Wilmington ', 'city' => 'Wilmington', 'region' => 'Delaware', 'country' => 'United States'],
            ['iata_code' => 'DAB', 'airport_name' => 'Daytona Beach Intl ', 'city' => 'Daytona Beach', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'FLL', 'airport_name' => 'Fort Lauderdale–Hollywood Intl ', 'city' => 'Fort Lauderdale', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'RSW', 'airport_name' => 'Southwest Florida Intl ', 'city' => 'Fort Myers', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'VPS', 'airport_name' => 'Destin–Fort Walton Beach  ', 'city' => 'Fort Walton Beach', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'GNV', 'airport_name' => 'Gainesville Regional ', 'city' => 'Gainesville', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'JAX', 'airport_name' => 'Jacksonville Intl ', 'city' => 'Jacksonville', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'EYW', 'airport_name' => 'Key West Intl ', 'city' => 'Key West', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'MLB', 'airport_name' => 'Melbourne Orlando Intl ', 'city' => 'Melbourne', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'MIA', 'airport_name' => 'Miami Intl ', 'city' => 'Miami', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'MCO', 'airport_name' => 'Orlando Intl ', 'city' => 'Orlando', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'ECP', 'airport_name' => 'Northwest Florida Beaches Intl ', 'city' => 'Panama City', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'PNS', 'airport_name' => 'Pensacola Intl ', 'city' => 'Pensacola', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'PGD', 'airport_name' => 'Punta Gorda ', 'city' => 'Punta Gorda', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'SFB', 'airport_name' => 'Orlando Sanford Intl ', 'city' => 'Sanford', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'SRQ', 'airport_name' => 'Sarasota–Bradenton Intl ', 'city' => 'Sarasota', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'PIE', 'airport_name' => 'St. Pete–Clearwater Intl ', 'city' => 'St. Petersburg', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'TLH', 'airport_name' => 'Tallahassee Intl ', 'city' => 'Tallahassee', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'TPA', 'airport_name' => 'Tampa Intl ', 'city' => 'Tampa', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'PBI', 'airport_name' => 'Palm Beach Intl ', 'city' => 'West Palm Beach', 'region' => 'Florida', 'country' => 'United States'],
            ['iata_code' => 'ABY', 'airport_name' => 'Southwest Georgia Regional ', 'city' => 'Albany', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'ATL', 'airport_name' => 'Hartsfield–Jackson Atlanta Intl ', 'city' => 'Atlanta', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'AGS', 'airport_name' => 'Augusta Regional  ', 'city' => 'Augusta', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'BQK', 'airport_name' => 'Brunswick Golden Isles ', 'city' => 'Brunswick', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'CSG', 'airport_name' => 'Columbus ', 'city' => 'Columbus', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'MCN', 'airport_name' => 'Middle Georgia Regional ', 'city' => 'Macon', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'SAV', 'airport_name' => 'Savannah/Hilton Head Intl ', 'city' => 'Savannah', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'VLD', 'airport_name' => 'Valdosta Regional ', 'city' => 'Valdosta', 'region' => 'Georgia', 'country' => 'United States'],
            ['iata_code' => 'ITO', 'airport_name' => 'Hilo Intl ', 'city' => 'Hilo, Hawaii', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'HNL', 'airport_name' => 'Daniel K. Inouye Intl ', 'city' => 'Honolulu, Oahu', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'OGG', 'airport_name' => 'Kahului ', 'city' => 'Kahului, Maui', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'KOA', 'airport_name' => 'Ellison Onizuka Kona Intl  at Keahole', 'city' => 'Kailua-Kona, Hawaii', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'MKK', 'airport_name' => 'Molokai  ', 'city' => 'Kaunakakai, Molokai', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'LNY', 'airport_name' => 'Lanai ', 'city' => 'Lanai City, Lanai', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'LIH', 'airport_name' => 'Lihue ', 'city' => 'Lihue, Kauai', 'region' => 'Hawaii', 'country' => 'United States'],
            ['iata_code' => 'BOI', 'airport_name' => 'Boise Air Terminal Gowen Field', 'city' => 'Boise', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'SUN', 'airport_name' => 'Friedman Memorial ', 'city' => 'Hailey / Sun Valley', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'IDA', 'airport_name' => 'Idaho Falls Regional  ', 'city' => 'Idaho Falls', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'LWS', 'airport_name' => 'Lewiston–Nez Perce County ', 'city' => 'Lewiston', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'PIH', 'airport_name' => 'Pocatello Regional ', 'city' => 'Pocatello', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'TWF', 'airport_name' => 'Magic Valley Regional ', 'city' => 'Twin Falls', 'region' => 'Idaho', 'country' => 'United States'],
            ['iata_code' => 'BLV', 'airport_name' => 'MidAmerica St. Louis  ', 'city' => 'Belleville', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'BMI', 'airport_name' => 'Central Illinois Regional  at Bloomington-Normal', 'city' => 'Bloomington ', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'CMI', 'airport_name' => 'University of Illinois - Willard ', 'city' => 'Champaign ', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'MDW', 'airport_name' => 'Chicago Midway Intl ', 'city' => 'Chicago', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'ORD', 'airport_name' => 'Chicago O\'Hare Intl ', 'city' => 'Chicago', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'DEC', 'airport_name' => 'Decatur ', 'city' => 'Decatur', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'MWA', 'airport_name' => 'Veterans  of Southern Illinois', 'city' => 'Marion', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'MLI', 'airport_name' => 'Quad Cities Intl ', 'city' => 'Moline', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'PIA', 'airport_name' => 'Peoria Intl ', 'city' => 'Peoria', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'RFD', 'airport_name' => 'Chicago Rockford Intl  ', 'city' => 'Rockford', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'SPI', 'airport_name' => 'Abraham Lincoln Capital ', 'city' => 'Springfield', 'region' => 'Illinois', 'country' => 'United States'],
            ['iata_code' => 'EVV', 'airport_name' => 'Evansville Regional ', 'city' => 'Evansville', 'region' => 'Indiana', 'country' => 'United States'],
            ['iata_code' => 'FWA', 'airport_name' => 'Fort Wayne Intl ', 'city' => 'Fort Wayne', 'region' => 'Indiana', 'country' => 'United States'],
            ['iata_code' => 'IND', 'airport_name' => 'Indianapolis Intl ', 'city' => 'Indianapolis', 'region' => 'Indiana', 'country' => 'United States'],
            ['iata_code' => 'SBN', 'airport_name' => 'South Bend Intl ', 'city' => 'South Bend', 'region' => 'Indiana', 'country' => 'United States'],
            ['iata_code' => 'CID', 'airport_name' => 'Eastern Iowa ', 'city' => 'Cedar Rapids', 'region' => 'Iowa', 'country' => 'United States'],
            ['iata_code' => 'DSM', 'airport_name' => 'Des Moines Intl ', 'city' => 'Des Moines', 'region' => 'Iowa', 'country' => 'United States'],
            ['iata_code' => 'DBQ', 'airport_name' => 'Dubuque Regional ', 'city' => 'Dubuque', 'region' => 'Iowa', 'country' => 'United States'],
            ['iata_code' => 'SUX', 'airport_name' => 'Sioux Gateway ', 'city' => 'Sioux City', 'region' => 'Iowa', 'country' => 'United States'],
            ['iata_code' => 'ALO', 'airport_name' => 'Waterloo Regional ', 'city' => 'Waterloo', 'region' => 'Iowa', 'country' => 'United States'],
            ['iata_code' => 'GCK', 'airport_name' => 'Garden City Regional ', 'city' => 'Garden City', 'region' => 'Kansas', 'country' => 'United States'],
            ['iata_code' => 'HYS', 'airport_name' => 'Hays Regional ', 'city' => 'Hays', 'region' => 'Kansas', 'country' => 'United States'],
            ['iata_code' => 'MHK', 'airport_name' => 'Manhattan Regional ', 'city' => 'Manhattan', 'region' => 'Kansas', 'country' => 'United States'],
            ['iata_code' => 'SLN', 'airport_name' => 'Salina Regional ', 'city' => 'Salina', 'region' => 'Kansas', 'country' => 'United States'],
            ['iata_code' => 'ICT', 'airport_name' => 'Dwight D. Eisenhower  ', 'city' => 'Wichita', 'region' => 'Kansas', 'country' => 'United States'],
            ['iata_code' => 'CVG', 'airport_name' => 'Cincinnati Northern Kentucky Intl ', 'city' => 'Cincinnati', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'LEX', 'airport_name' => 'Blue Grass ', 'city' => 'Lexington', 'region' => 'Kentucky', 'country' => 'United States'],
            ['iata_code' => 'SDF', 'airport_name' => 'Louisville Muhammad Ali Intl ', 'city' => 'Louisville', 'region' => 'Kentucky', 'country' => 'United States'],
            ['iata_code' => 'OWB', 'airport_name' => 'Daviess County Regional ', 'city' => 'Owensboro', 'region' => 'Kentucky', 'country' => 'United States'],
            ['iata_code' => 'PAH', 'airport_name' => 'Barkley Regional ', 'city' => 'Paducah', 'region' => 'Kentucky', 'country' => 'United States'],
            ['iata_code' => 'AEX', 'airport_name' => 'Alexandria Intl ', 'city' => 'Alexandria', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'BTR', 'airport_name' => 'Baton Rouge Metropolitan  (Ryan Field)', 'city' => 'Baton Rouge', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'LFT', 'airport_name' => 'Lafayette Regional  (Paul Fournet Field)', 'city' => 'Lafayette', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'LCH', 'airport_name' => 'Lake Charles Regional ', 'city' => 'Lake Charles', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'MLU', 'airport_name' => 'Monroe Regional ', 'city' => 'Monroe', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'MSY', 'airport_name' => 'Louis Armstrong New Orleans Intl ', 'city' => 'New Orleans', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'SHV', 'airport_name' => 'Shreveport Regional ', 'city' => 'Shreveport', 'region' => 'Louisiana', 'country' => 'United States'],
            ['iata_code' => 'BGR', 'airport_name' => 'Bangor Intl ', 'city' => 'Bangor', 'region' => 'Maine', 'country' => 'United States'],
            ['iata_code' => 'PWM', 'airport_name' => 'Portland Intl Jetport', 'city' => 'Portland', 'region' => 'Maine', 'country' => 'United States'],
            ['iata_code' => 'PQI', 'airport_name' => 'Presque Isle Intl ', 'city' => 'Presque Isle', 'region' => 'Maine', 'country' => 'United States'],
            ['iata_code' => 'RKD', 'airport_name' => 'Knox County Regional ', 'city' => 'Rockland', 'region' => 'Maine', 'country' => 'United States'],
            ['iata_code' => 'BWI', 'airport_name' => 'Baltimore/Washington Intl ', 'city' => 'Baltimore', 'region' => 'Maryland', 'country' => 'United States'],
            ['iata_code' => 'HGR', 'airport_name' => 'Hagerstown Regional  ', 'city' => 'Hagerstown', 'region' => 'Maryland', 'country' => 'United States'],
            ['iata_code' => 'SBY', 'airport_name' => 'Salisbury Regional ', 'city' => 'Salisbury', 'region' => 'Maryland', 'country' => 'United States'],
            ['iata_code' => 'BOS', 'airport_name' => 'Gen. Edward Lawrence Logan Intl ', 'city' => 'Boston', 'region' => 'Massachusetts', 'country' => 'United States'],
            ['iata_code' => 'HYA', 'airport_name' => 'Cape Cod Gateway  ', 'city' => 'Hyannis', 'region' => 'Massachusetts', 'country' => 'United States'],
            ['iata_code' => 'ACK', 'airport_name' => 'Nantucket Memorial ', 'city' => 'Nantucket', 'region' => 'Massachusetts', 'country' => 'United States'],
            ['iata_code' => 'MVY', 'airport_name' => 'Martha\'s Vineyard ', 'city' => 'Vineyard Haven', 'region' => 'Massachusetts', 'country' => 'United States'],
            ['iata_code' => 'ORH', 'airport_name' => 'Worcester Regional ', 'city' => 'Worcester', 'region' => 'Massachusetts', 'country' => 'United States'],
            ['iata_code' => 'APN', 'airport_name' => 'Alpena County Regional ', 'city' => 'Alpena', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'DTW', 'airport_name' => 'Detroit Metro Wayne County ', 'city' => 'Detroit', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'ESC', 'airport_name' => 'Delta County ', 'city' => 'Escanaba', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'FNT', 'airport_name' => 'Bishop Intl ', 'city' => 'Flint', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'GRR', 'airport_name' => 'Gerald R. Ford Intl ', 'city' => 'Grand Rapids', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'CMX', 'airport_name' => 'Houghton County Memorial ', 'city' => 'Hancock', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'IMT', 'airport_name' => 'Ford ', 'city' => 'Iron Mountain', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'AZO', 'airport_name' => 'Kalamazoo/Battle Creek Intl ', 'city' => 'Kalamazoo', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'LAN', 'airport_name' => 'Capital Region Intl  ', 'city' => 'Lansing', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'SAW', 'airport_name' => 'Marquette Sawyer Regional ', 'city' => 'Marquette', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'MKG', 'airport_name' => 'Muskegon County ', 'city' => 'Muskegon', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'PLN', 'airport_name' => 'Pellston Regional/Emmet County ', 'city' => 'Pellston', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'MBS', 'airport_name' => 'MBS Intl ', 'city' => 'Saginaw', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'CIU', 'airport_name' => 'Chippewa County Intl ', 'city' => 'Sault Ste. Marie', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'TVC', 'airport_name' => 'Cherry Capital  ', 'city' => 'Traverse City', 'region' => 'Michigan', 'country' => 'United States'],
            ['iata_code' => 'BJI', 'airport_name' => 'Bemidji Regional ', 'city' => 'Bemidji', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'BRD', 'airport_name' => 'Brainerd Lakes Regional ', 'city' => 'Brainerd', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'DLH', 'airport_name' => 'Duluth Intl ', 'city' => 'Duluth', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'HIB', 'airport_name' => 'Range Regional ', 'city' => 'Hibbing', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'MSP', 'airport_name' => 'Minneapolis–Saint Paul Intl  ', 'city' => 'Minneapolis-St. Paul', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'RST', 'airport_name' => 'Rochester Intl ', 'city' => 'Rochester', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'STC', 'airport_name' => 'St. Cloud Regional ', 'city' => 'St. Cloud', 'region' => 'Minnesota', 'country' => 'United States'],
            ['iata_code' => 'GTR', 'airport_name' => 'Golden Triangle Regional ', 'city' => 'Columbus', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'GPT', 'airport_name' => 'Gulfport–Biloxi Intl ', 'city' => 'Gulfport ', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'PIB', 'airport_name' => 'Hattiesburg–Laurel Regional ', 'city' => 'Laurel', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'JAN', 'airport_name' => 'Jackson–Medgar Wiley Evers Intl ', 'city' => 'Jackson', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'MEI', 'airport_name' => 'Key Field', 'city' => 'Meridian', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'TUP', 'airport_name' => 'Tupelo Regional  (C.D. Lemons Field)', 'city' => 'Tupelo', 'region' => 'Mississippi', 'country' => 'United States'],
            ['iata_code' => 'BKG', 'airport_name' => 'Branson ', 'city' => 'Branson', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'COU', 'airport_name' => 'Columbia Regional ', 'city' => 'Columbia', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'TBN', 'airport_name' => 'Waynesville–St. Robert Regional ', 'city' => 'Fort Leonard Wood ', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'JLN', 'airport_name' => 'Joplin Regional ', 'city' => 'Joplin', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'MCI', 'airport_name' => 'Kansas City Intl ', 'city' => 'Kansas City', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'STL', 'airport_name' => 'St. Louis Lambert Intl ', 'city' => 'St. Louis', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'SGF', 'airport_name' => 'Springfield–Branson National ', 'city' => 'Springfield', 'region' => 'Missouri', 'country' => 'United States'],
            ['iata_code' => 'BIL', 'airport_name' => 'Billings Logan Intl ', 'city' => 'Billings', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'BZN', 'airport_name' => 'Bozeman Yellowstone Intl ', 'city' => 'Bozeman', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'BTM', 'airport_name' => 'Bert Mooney ', 'city' => 'Butte', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'GTF', 'airport_name' => 'Great Falls Intl ', 'city' => 'Great Falls', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'HLN', 'airport_name' => 'Helena Regional ', 'city' => 'Helena', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'GPI', 'airport_name' => 'Glacier Park Intl ', 'city' => 'Kalispell', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'MSO', 'airport_name' => 'Missoula Montana  ', 'city' => 'Missoula', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'WYS', 'airport_name' => 'Yellowstone ', 'city' => 'West Yellowstone', 'region' => 'Montana', 'country' => 'United States'],
            ['iata_code' => 'GRI', 'airport_name' => 'Central Nebraska Regional ', 'city' => 'Grand Island', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'EAR', 'airport_name' => 'Kearney Regional  ', 'city' => 'Kearney', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'LNK', 'airport_name' => 'Lincoln  ', 'city' => 'Lincoln', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'LBF', 'airport_name' => 'North Platte Regional  Lee Bird Field', 'city' => 'North Platte', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'OMA', 'airport_name' => 'Eppley Airfield', 'city' => 'Omaha', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'BFF', 'airport_name' => 'Western Nebraska Regional Apt William B. Heilig Field', 'city' => 'Scottsbluff', 'region' => 'Nebraska', 'country' => 'United States'],
            ['iata_code' => 'BLD', 'airport_name' => 'Boulder City Municipal ', 'city' => 'Boulder City', 'region' => 'Nevada', 'country' => 'United States'],
            ['iata_code' => 'EKO', 'airport_name' => 'Elko Regional  (J.C. Harris Field)', 'city' => 'Elko', 'region' => 'Nevada', 'country' => 'United States'],
            ['iata_code' => 'LAS', 'airport_name' => 'Harry Reid Intl ', 'city' => 'Las Vegas', 'region' => 'Nevada', 'country' => 'United States'],
            ['iata_code' => 'RNO', 'airport_name' => 'Reno/Tahoe Intl ', 'city' => 'Reno', 'region' => 'Nevada', 'country' => 'United States'],
            ['iata_code' => 'MHT', 'airport_name' => 'Manchester–Boston Regional ', 'city' => 'Manchester', 'region' => 'New Hampshire', 'country' => 'United States'],
            ['iata_code' => 'PSM', 'airport_name' => 'Portsmouth Intl  at Pease', 'city' => 'Portsmouth', 'region' => 'New Hampshire', 'country' => 'United States'],
            ['iata_code' => 'ACY', 'airport_name' => 'Atlantic City Intl ', 'city' => 'Atlantic City', 'region' => 'New Jersey', 'country' => 'United States'],
            ['iata_code' => 'EWR', 'airport_name' => 'Newark Liberty Intl ', 'city' => 'Newark', 'region' => 'New Jersey', 'country' => 'United States'],
            ['iata_code' => 'TTN', 'airport_name' => 'Trenton–Mercer ', 'city' => 'Trenton', 'region' => 'New Jersey', 'country' => 'United States'],
            ['iata_code' => 'ABQ', 'airport_name' => 'Albuquerque Intl Sunport', 'city' => 'Albuquerque', 'region' => 'New Mexico', 'country' => 'United States'],
            ['iata_code' => 'HOB', 'airport_name' => 'Lea County Regional ', 'city' => 'Hobbs', 'region' => 'New Mexico', 'country' => 'United States'],
            ['iata_code' => 'ROW', 'airport_name' => 'Roswell Air Center', 'city' => 'Roswell', 'region' => 'New Mexico', 'country' => 'United States'],
            ['iata_code' => 'SAF', 'airport_name' => 'Santa Fe Municipal ', 'city' => 'Santa Fe', 'region' => 'New Mexico', 'country' => 'United States'],
            ['iata_code' => 'ALB', 'airport_name' => 'Albany Intl ', 'city' => 'Albany', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'BGM', 'airport_name' => 'Greater Binghamton  (Edwin A. Link Field)', 'city' => 'Binghamton', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'BUF', 'airport_name' => 'Buffalo Niagara Intl ', 'city' => 'Buffalo', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'ELM', 'airport_name' => 'Corning Regional ', 'city' => 'Elmira ', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'ITH', 'airport_name' => 'Tompkins Intl ', 'city' => 'Ithaca', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'JFK', 'airport_name' => 'John F. Kennedy Intl  ', 'city' => 'New York', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'LGA', 'airport_name' => 'LaGuardia  ', 'city' => 'New York', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'ISP', 'airport_name' => 'Long Island MacArthur ', 'city' => 'Islip', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'SWF', 'airport_name' => 'New York Stewart Intl ', 'city' => 'Newburgh', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'IAG', 'airport_name' => 'Niagara Falls Intl ', 'city' => 'Niagara Falls', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'OGS', 'airport_name' => 'Ogdensburg Intl ', 'city' => 'Ogdensburg', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'PBG', 'airport_name' => 'Plattsburgh Intl ', 'city' => 'Plattsburgh', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'ROC', 'airport_name' => 'Greater Rochester Intl ', 'city' => 'Rochester', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'SYR', 'airport_name' => 'Syracuse Hancock Intl ', 'city' => 'Syracuse', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'ART', 'airport_name' => 'Watertown Intl ', 'city' => 'Watertown', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'HPN', 'airport_name' => 'Westchester County ', 'city' => 'White Plains', 'region' => 'New York', 'country' => 'United States'],
            ['iata_code' => 'AVL', 'airport_name' => 'Asheville Regional ', 'city' => 'Asheville', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'CLT', 'airport_name' => 'Charlotte Douglas Intl ', 'city' => 'Charlotte', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'JQF', 'airport_name' => 'Concord–Padgett Regional ', 'city' => 'Concord', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'FAY', 'airport_name' => 'Fayetteville Regional  (Grannis Field)', 'city' => 'Fayetteville', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'GSO', 'airport_name' => 'Piedmont Triad Intl ', 'city' => 'Greensboro', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'PGV', 'airport_name' => 'Pitt–Greenville ', 'city' => 'Greenville', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'OAJ', 'airport_name' => 'Albert J. Ellis ', 'city' => 'Jacksonville', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'EWN', 'airport_name' => 'Coastal Carolina Regional  ', 'city' => 'New Bern', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'RDU', 'airport_name' => 'Raleigh–Durham Intl ', 'city' => 'Raleigh', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'ILM', 'airport_name' => 'Wilmington Intl ', 'city' => 'Wilmington', 'region' => 'North Carolina', 'country' => 'United States'],
            ['iata_code' => 'BIS', 'airport_name' => 'Bismarck Municipal ', 'city' => 'Bismarck', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'DIK', 'airport_name' => 'Dickinson Theodore Roosevelt Regional ', 'city' => 'Dickinson', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'FAR', 'airport_name' => 'Hector Intl ', 'city' => 'Fargo', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'GFK', 'airport_name' => 'Grand Forks Intl ', 'city' => 'Grand Forks', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'JMS', 'airport_name' => 'Jamestown Regional ', 'city' => 'Jamestown', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'MOT', 'airport_name' => 'Minot Intl ', 'city' => 'Minot', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'XWA', 'airport_name' => 'Williston Basin Intl ', 'city' => 'Williston', 'region' => 'North Dakota', 'country' => 'United States'],
            ['iata_code' => 'CAK', 'airport_name' => 'Akron–Canton Regional ', 'city' => 'Akron ', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'CLE', 'airport_name' => 'Cleveland Hopkins Intl ', 'city' => 'Cleveland', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'CMH', 'airport_name' => 'John Glenn Columbus Intl ', 'city' => 'Columbus', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'LCK', 'airport_name' => 'Rickenbacker Intl ', 'city' => 'Columbus', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'DAY', 'airport_name' => 'James M. Cox Dayton Intl ', 'city' => 'Dayton', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'TOL', 'airport_name' => 'Eugene F. Kranz Toledo Express ', 'city' => 'Toledo', 'region' => 'Ohio', 'country' => 'United States'],
            ['iata_code' => 'LAW', 'airport_name' => 'Lawton–Fort Sill Regional ', 'city' => 'Lawton', 'region' => 'Oklahoma', 'country' => 'United States'],
            ['iata_code' => 'OKC', 'airport_name' => 'OKC Will Rogers Intl ', 'city' => 'Oklahoma City', 'region' => 'Oklahoma', 'country' => 'United States'],
            ['iata_code' => 'SWO', 'airport_name' => 'Stillwater Regional ', 'city' => 'Stillwater', 'region' => 'Oklahoma', 'country' => 'United States'],
            ['iata_code' => 'TUL', 'airport_name' => 'Tulsa Intl ', 'city' => 'Tulsa', 'region' => 'Oklahoma', 'country' => 'United States'],
            ['iata_code' => 'EUG', 'airport_name' => 'Mahlon Sweet Field', 'city' => 'Eugene', 'region' => 'Oregon', 'country' => 'United States'],
            ['iata_code' => 'MFR', 'airport_name' => 'Rogue Valley Intl–Medford ', 'city' => 'Medford', 'region' => 'Oregon', 'country' => 'United States'],
            ['iata_code' => 'OTH', 'airport_name' => 'Southwest Oregon Regional ', 'city' => 'North Bend', 'region' => 'Oregon', 'country' => 'United States'],
            ['iata_code' => 'PDX', 'airport_name' => 'Portland Intl ', 'city' => 'Portland', 'region' => 'Oregon', 'country' => 'United States'],
            ['iata_code' => 'RDM', 'airport_name' => 'Roberts Field', 'city' => 'Redmond', 'region' => 'Oregon', 'country' => 'United States'],
            ['iata_code' => 'ABE', 'airport_name' => 'Lehigh Valley Intl  ', 'city' => 'Allentown', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'ERI', 'airport_name' => 'Erie Intl  (Tom Ridge Field)', 'city' => 'Erie', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'MDT', 'airport_name' => 'Harrisburg Intl ', 'city' => 'Harrisburg', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'LBE', 'airport_name' => 'Arnold Palmer Regional ', 'city' => 'Latrobe', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'PHL', 'airport_name' => 'Philadelphia Intl ', 'city' => 'Philadelphia', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'PIT', 'airport_name' => 'Pittsburgh Intl ', 'city' => 'Pittsburgh', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'UNV', 'airport_name' => 'State College Regional ', 'city' => 'State College', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'AVP', 'airport_name' => 'Wilkes-Barre/Scranton Intl ', 'city' => 'Wilkes-Barre ', 'region' => 'Pennsylvania', 'country' => 'United States'],
            ['iata_code' => 'BID', 'airport_name' => 'Block Island State ', 'city' => 'Block Island', 'region' => 'Rhode Island', 'country' => 'United States'],
            ['iata_code' => 'PVD', 'airport_name' => 'Rhode Island T. F. Green Intl ', 'city' => 'Providence', 'region' => 'Rhode Island', 'country' => 'United States'],
            ['iata_code' => 'WST', 'airport_name' => 'Westerly State ', 'city' => 'Westerly', 'region' => 'Rhode Island', 'country' => 'United States'],
            ['iata_code' => 'CHS', 'airport_name' => 'Charleston Intl  ', 'city' => 'Charleston', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'CAE', 'airport_name' => 'Columbia Metropolitan ', 'city' => 'Columbia', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'FLO', 'airport_name' => 'Florence Regional ', 'city' => 'Florence', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'GSP', 'airport_name' => 'Greenville–Spartanburg Intl  ', 'city' => 'Greenville', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'HXD', 'airport_name' => 'Hilton Head ', 'city' => 'Hilton Head', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'MYR', 'airport_name' => 'Myrtle Beach Intl ', 'city' => 'Myrtle Beach', 'region' => 'South Carolina', 'country' => 'United States'],
            ['iata_code' => 'ABR', 'airport_name' => 'Aberdeen Regional ', 'city' => 'Aberdeen', 'region' => 'South Dakota', 'country' => 'United States'],
            ['iata_code' => 'PIR', 'airport_name' => 'Pierre Regional ', 'city' => 'Pierre', 'region' => 'South Dakota', 'country' => 'United States'],
            ['iata_code' => 'RAP', 'airport_name' => 'Rapid City Regional ', 'city' => 'Rapid City', 'region' => 'South Dakota', 'country' => 'United States'],
            ['iata_code' => 'FSD', 'airport_name' => 'Joe Foss Field ', 'city' => 'Sioux Falls', 'region' => 'South Dakota', 'country' => 'United States'],
            ['iata_code' => 'ATY', 'airport_name' => 'Watertown Regional ', 'city' => 'Watertown', 'region' => 'South Dakota', 'country' => 'United States'],
            ['iata_code' => 'CHA', 'airport_name' => 'Chattanooga Metropolitan ', 'city' => 'Chattanooga', 'region' => 'Tennessee', 'country' => 'United States'],
            ['iata_code' => 'TYS', 'airport_name' => 'McGhee Tyson ', 'city' => 'Knoxville', 'region' => 'Tennessee', 'country' => 'United States'],
            ['iata_code' => 'MEM', 'airport_name' => 'Memphis Intl ', 'city' => 'Memphis', 'region' => 'Tennessee', 'country' => 'United States'],
            ['iata_code' => 'BNA', 'airport_name' => 'Nashville Intl ', 'city' => 'Nashville', 'region' => 'Tennessee', 'country' => 'United States'],
            ['iata_code' => 'TRI', 'airport_name' => 'Tri-Cities ', 'city' => 'Tri-Cities', 'region' => 'Tennessee', 'country' => 'United States'],
            ['iata_code' => 'ABI', 'airport_name' => 'Abilene Regional ', 'city' => 'Abilene', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'AMA', 'airport_name' => 'Rick Husband Amarillo Intl ', 'city' => 'Amarillo', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'AUS', 'airport_name' => 'Austin–Bergstrom Intl ', 'city' => 'Austin', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'BPT', 'airport_name' => 'Jack Brooks Regional  ', 'city' => 'Beaumont', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'BRO', 'airport_name' => 'South Padre Island Intl ', 'city' => 'Brownsville', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'CLL', 'airport_name' => 'Easterwood Field', 'city' => 'College Station', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'CRP', 'airport_name' => 'Corpus Christi Intl ', 'city' => 'Corpus Christi', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'DAL', 'airport_name' => 'Dallas Love Field', 'city' => 'Dallas', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'DFW', 'airport_name' => 'Dallas Fort Worth Intl ', 'city' => 'Dallas–Fort Worth', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'DRT', 'airport_name' => 'Del Rio Intl ', 'city' => 'Del Rio', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'ELP', 'airport_name' => 'El Paso Intl ', 'city' => 'El Paso', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'HRL', 'airport_name' => 'Valley Intl ', 'city' => 'Harlingen', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'IAH', 'airport_name' => 'George Bush Intercontinental  ', 'city' => 'Houston', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'HOU', 'airport_name' => 'William P. Hobby ', 'city' => 'Houston', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'GRK', 'airport_name' => 'Fort Hood Regional   ', 'city' => 'Killeen', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'LRD', 'airport_name' => 'Laredo Intl ', 'city' => 'Laredo', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'GGG', 'airport_name' => 'East Texas Regional ', 'city' => 'Longview', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'LBB', 'airport_name' => 'Lubbock Preston Smith Intl ', 'city' => 'Lubbock', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'MFE', 'airport_name' => 'McAllen Miller Intl ', 'city' => 'McAllen', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'MAF', 'airport_name' => 'Midland Intl Air and Space Port', 'city' => 'Midland', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'SJT', 'airport_name' => 'San Angelo Regional  (Mathis Field)', 'city' => 'San Angelo', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'SAT', 'airport_name' => 'San Antonio Intl ', 'city' => 'San Antonio', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'TYR', 'airport_name' => 'Tyler Pounds Regional ', 'city' => 'Tyler', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'ACT', 'airport_name' => 'Waco Regional ', 'city' => 'Waco', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'SPS', 'airport_name' => 'Wichita Falls Regional  ', 'city' => 'Wichita Falls', 'region' => 'Texas', 'country' => 'United States'],
            ['iata_code' => 'CDC', 'airport_name' => 'Cedar City Regional ', 'city' => 'Cedar City', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'CNY', 'airport_name' => 'Canyonlands Regional ', 'city' => 'Moab', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'OGD', 'airport_name' => 'Ogden–Hinckley ', 'city' => 'Ogden', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'PVU', 'airport_name' => 'Provo Municipal ', 'city' => 'Provo', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'SGU', 'airport_name' => 'St. George Regional ', 'city' => 'St. George', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'SLC', 'airport_name' => 'Salt Lake City Intl ', 'city' => 'Salt Lake City', 'region' => 'Utah', 'country' => 'United States'],
            ['iata_code' => 'BTV', 'airport_name' => 'Patrick Leahy Burlington Intl ', 'city' => 'Burlington', 'region' => 'Vermont', 'country' => 'United States'],
            ['iata_code' => 'CHO', 'airport_name' => 'Charlottesville–Albemarle ', 'city' => 'Charlottesville', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'LYH', 'airport_name' => 'Lynchburg Regional  ', 'city' => 'Lynchburg', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'PHF', 'airport_name' => 'Newport News/Williamsburg Intl  ', 'city' => 'Newport News', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'ORF', 'airport_name' => 'Norfolk Intl ', 'city' => 'Norfolk', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'RIC', 'airport_name' => 'Richmond Intl  (Byrd Field)', 'city' => 'Richmond', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'ROA', 'airport_name' => 'Roanoke–Blacksburg Regional  ', 'city' => 'Roanoke', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'SHD', 'airport_name' => 'Shenandoah Valley Regional ', 'city' => 'Staunton', 'region' => 'Virginia', 'country' => 'United States'],
            ['iata_code' => 'DCA', 'airport_name' => 'Ronald Reagan Washington National ', 'city' => 'Washington', 'region' => 'District of Columbia', 'country' => 'United States'],
            ['iata_code' => 'IAD', 'airport_name' => 'Washington Dulles Intl ', 'city' => 'Washington', 'region' => 'District of Columbia', 'country' => 'United States'],
            ['iata_code' => 'BLI', 'airport_name' => 'Bellingham Intl ', 'city' => 'Bellingham', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'ORS', 'airport_name' => 'Orcas Island ', 'city' => 'Eastsound', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'PAE', 'airport_name' => 'Paine Field (Snohomish County )', 'city' => 'Everett', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'FHR', 'airport_name' => 'Friday Harbor ', 'city' => 'Friday Harbor', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'PSC', 'airport_name' => 'Tri-Cities ', 'city' => 'Pasco', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'PUW', 'airport_name' => 'Pullman–Moscow Regional ', 'city' => 'Pullman', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'BFI', 'airport_name' => 'Boeing field-King County Intl  ', 'city' => 'Seattle', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'SEA', 'airport_name' => 'Seattle–Tacoma Intl ', 'city' => 'Seattle', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'GEG', 'airport_name' => 'Spokane Intl  (Geiger Field)', 'city' => 'Spokane', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'ALW', 'airport_name' => 'Walla Walla Regional ', 'city' => 'Walla Walla', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'EAT', 'airport_name' => 'Pangborn Memorial ', 'city' => 'Wenatchee', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'YKM', 'airport_name' => 'Yakima Air Terminal (McAllister Field)', 'city' => 'Yakima', 'region' => 'Washington', 'country' => 'United States'],
            ['iata_code' => 'CRW', 'airport_name' => 'Yeager ', 'city' => 'Charleston', 'region' => 'West Virginia', 'country' => 'United States'],
            ['iata_code' => 'CKB', 'airport_name' => 'North Central West Virginia  ', 'city' => 'Clarksburg', 'region' => 'West Virginia', 'country' => 'United States'],
            ['iata_code' => 'HTS', 'airport_name' => 'Tri-State  Milton J. Ferguson Field', 'city' => 'Huntington', 'region' => 'West Virginia', 'country' => 'United States'],
            ['iata_code' => 'LWB', 'airport_name' => 'Greenbrier Valley ', 'city' => 'Lewisburg', 'region' => 'West Virginia', 'country' => 'United States'],
            ['iata_code' => 'ATW', 'airport_name' => 'Appleton Intl ', 'city' => 'Appleton', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'EAU', 'airport_name' => 'Chippewa Valley Regional ', 'city' => 'Eau Claire', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'GRB', 'airport_name' => 'Green Bay–Austin Straubel Intl ', 'city' => 'Green Bay', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'LSE', 'airport_name' => 'La Crosse Regional ', 'city' => 'La Crosse', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'MSN', 'airport_name' => 'Dane County Regional  (Truax Field)', 'city' => 'Madison', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'MKE', 'airport_name' => 'Milwaukee Mitchell Intl ', 'city' => 'Milwaukee', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'CWA', 'airport_name' => 'Central Wisconsin ', 'city' => 'Mosinee', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'RHI', 'airport_name' => 'Rhinelander–Oneida County ', 'city' => 'Rhinelander', 'region' => 'Wisconsin', 'country' => 'United States'],
            ['iata_code' => 'CPR', 'airport_name' => 'Casper–Natrona County Intl ', 'city' => 'Casper', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'COD', 'airport_name' => 'Yellowstone Regional ', 'city' => 'Cody', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'GCC', 'airport_name' => 'Gillette–Campbell County ', 'city' => 'Gillette', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'JAC', 'airport_name' => 'Jackson Hole ', 'city' => 'Jackson', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'LAR', 'airport_name' => 'Laramie Regional ', 'city' => 'Laramie', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'RIW', 'airport_name' => 'Central Wyoming Regional  ', 'city' => 'Riverton', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'RKS', 'airport_name' => 'Southwest Wyoming Regional  ', 'city' => 'Rock Springs', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'SHR', 'airport_name' => 'Sheridan County ', 'city' => 'Sheridan', 'region' => 'Wyoming', 'country' => 'United States'],
            ['iata_code' => 'GUM', 'airport_name' => 'Antonio B. Won Pat Intl ', 'city' => 'Hagåtña , Tamuning', 'region' => 'Guam', 'country' => 'United States'],
            ['iata_code' => 'BQN', 'airport_name' => 'Rafael Hernández ', 'city' => 'Aguadilla', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'RVR', 'airport_name' => 'José Aponte de la Torre ', 'city' => 'Ceiba', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'CPX', 'airport_name' => 'Benjamín Rivera Noriega ', 'city' => 'Culebra', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'PSE', 'airport_name' => 'Mercedita ', 'city' => 'Ponce', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'SIG', 'airport_name' => 'Fernando Luis Ribas Dominicci ', 'city' => 'San Juan', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'SJU', 'airport_name' => 'Luis Muñoz Marín Intl ', 'city' => 'San Juan', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'VQS', 'airport_name' => 'Antonio Rivera Rodríguez ', 'city' => 'Vieques', 'region' => 'Puerto Rico', 'country' => 'United States'],
            ['iata_code' => 'STT', 'airport_name' => 'Cyril E. King ', 'city' => 'Charlotte Amalie', 'region' => 'Virgin Islands', 'country' => 'United States'],
            ['iata_code' => 'STX', 'airport_name' => 'Henry E. Rohlsen ', 'city' => 'Christiansted', 'region' => 'Virgin Islands', 'country' => 'United States'],
            ['iata_code' => 'DEL', 'airport_name' => 'Indira Gandhi Intl ', 'city' => 'Delhi NCR', 'region' => 'Delhi (NCT)', 'country' => 'India'],
            ['iata_code' => 'BOM', 'airport_name' => 'Chhatrapati Shivaji Intl ', 'city' => 'Mumbai', 'region' => 'Maharashtra', 'country' => 'India'],
            ['iata_code' => 'BLR', 'airport_name' => 'Kempegowda Intl ', 'city' => 'Bengaluru', 'region' => 'Karnataka', 'country' => 'India'],
            ['iata_code' => 'HYD', 'airport_name' => 'Rajiv Gandhi Intl ', 'city' => 'Hyderabad', 'region' => 'Telangana', 'country' => 'India'],
            ['iata_code' => 'MAA', 'airport_name' => 'Chennai Intl ', 'city' => 'Chennai', 'region' => 'Tamil Nadu', 'country' => 'India'],
            ['iata_code' => 'CCU', 'airport_name' => 'Netaji S. Chandra Intl ', 'city' => 'Kolkata', 'region' => 'West Bengal', 'country' => 'India'],
            ['iata_code' => 'AMD', 'airport_name' => 'Sardar Vallabhbhai Patel Intl ', 'city' => 'Ahmedabad', 'region' => 'Gujarat', 'country' => 'India'],
            ['iata_code' => 'COK', 'airport_name' => 'Cochin Intl ', 'city' => 'Kochi', 'region' => 'Kerala', 'country' => 'India'],
            ['iata_code' => 'PNQ', 'airport_name' => 'Pune ', 'city' => 'Pune', 'region' => 'Maharashtra', 'country' => 'India'],
            ['iata_code' => 'GOI', 'airport_name' => 'Dabolim ', 'city' => 'Dabolim', 'region' => 'Goa', 'country' => 'India'],
            ['iata_code' => 'LKO', 'airport_name' => 'Chaudhary Charan Singh Intl ', 'city' => 'Lucknow', 'region' => 'Uttar Pradesh', 'country' => 'India'],
            ['iata_code' => 'GAU', 'airport_name' => 'Lokpriya Gopinath Bordoloi Intl ', 'city' => 'Guwahati', 'region' => 'Assam', 'country' => 'India'],
            ['iata_code' => 'JAI', 'airport_name' => 'Jaipur Intl ', 'city' => 'Jaipur', 'region' => 'Rajasthan', 'country' => 'India'],
            ['iata_code' => 'TRV', 'airport_name' => 'Trivandrum Intl ', 'city' => 'Thiruvananthapuram', 'region' => 'Kerala', 'country' => 'India'],
            ['iata_code' => 'BBI', 'airport_name' => 'Biju Patnaik Intl ', 'city' => 'Bhubaneswar', 'region' => 'Odisha', 'country' => 'India'],
            ['iata_code' => 'GOX', 'airport_name' => 'Manohar Intl ', 'city' => 'Mopa', 'region' => 'Goa', 'country' => 'India'],
            ['iata_code' => 'SXR', 'airport_name' => 'Srinagar ', 'city' => 'Srinagar', 'region' => 'Jammu & Kashmir (UT)', 'country' => 'India'],
            ['iata_code' => 'IXC', 'airport_name' => 'Chandigarh ', 'city' => 'Chandigarh', 'region' => 'Chandigarh (UT)', 'country' => 'India'],
            ['iata_code' => 'VNS', 'airport_name' => 'Lal Bahadur Shastri Intl ', 'city' => 'Varanasi', 'region' => 'Uttar Pradesh', 'country' => 'India'],
            ['iata_code' => 'PAT', 'airport_name' => 'Jay Prakash Narayan ', 'city' => 'Patna', 'region' => 'Bihar', 'country' => 'India'],
            ['iata_code' => 'IDR', 'airport_name' => 'Devi Ahilyabai Holkar Intl ', 'city' => 'Indore', 'region' => 'Madhya Pradesh', 'country' => 'India'],
            ['iata_code' => 'CCJ', 'airport_name' => 'Calicut Intl ', 'city' => 'Kozhikode', 'region' => 'Kerala', 'country' => 'India'],
            ['iata_code' => 'ATQ', 'airport_name' => 'Sri Guru Ram Dass Jee Intl ', 'city' => 'Amritsar', 'region' => 'Punjab', 'country' => 'India'],
            ['iata_code' => 'CJB', 'airport_name' => 'Coimbatore Intl ', 'city' => 'Coimbatore', 'region' => 'Tamil Nadu', 'country' => 'India'],
            ['iata_code' => 'IXB', 'airport_name' => 'Bagdogra Intl ', 'city' => 'Siliguri', 'region' => 'West Bengal', 'country' => 'India'],
            ['iata_code' => 'VTZ', 'airport_name' => 'Visakhapatnam Intl ', 'city' => 'Visakhapatnam', 'region' => 'Andhra Pradesh', 'country' => 'India'],
            ['iata_code' => 'NAG', 'airport_name' => 'Dr. Babasaheb Ambedkar Intl ', 'city' => 'Nagpur', 'region' => 'Maharashtra', 'country' => 'India'],
            ['iata_code' => 'RPR', 'airport_name' => 'Swami Vivekananda ', 'city' => 'Raipur', 'region' => 'Chhattisgarh', 'country' => 'India'],
            ['iata_code' => 'IXR', 'airport_name' => 'Birsa Munda ', 'city' => 'Ranchi', 'region' => 'Jharkhand', 'country' => 'India'],
            ['iata_code' => 'IXE', 'airport_name' => 'Mangalore Intl ', 'city' => 'Mangalore', 'region' => 'Karnataka', 'country' => 'India'],
            ['iata_code' => 'TRZ', 'airport_name' => 'Tiruchirappalli Intl ', 'city' => 'Tiruchirappalli', 'region' => 'Tamil Nadu', 'country' => 'India'],
            ['iata_code' => 'DED', 'airport_name' => 'Jolly Grant ', 'city' => 'Dehradun', 'region' => 'Uttarakhand', 'country' => 'India'],
            ['iata_code' => 'STV', 'airport_name' => 'Surat Intl ', 'city' => 'Surat', 'region' => 'Gujarat', 'country' => 'India'],
            ['iata_code' => 'IXZ', 'airport_name' => 'Veer Savarkar ', 'city' => 'Port Blair', 'region' => 'Andaman & Nicobar Islands (UT)', 'country' => 'India'],
            ['iata_code' => 'UDR', 'airport_name' => 'Maharana Pratap ', 'city' => 'Udaipur', 'region' => 'Rajasthan', 'country' => 'India'],
            ['iata_code' => 'IXJ', 'airport_name' => 'Jammu ', 'city' => 'Jammu', 'region' => 'Jammu & Kashmir (UT)', 'country' => 'India'],
            ['iata_code' => 'BHO', 'airport_name' => 'Bhopal ', 'city' => 'Bhopal', 'region' => 'Madhya Pradesh', 'country' => 'India'],
            ['iata_code' => 'IXA', 'airport_name' => 'Maharaja Bir Bikram ', 'city' => 'Agartala', 'region' => 'Tripura', 'country' => 'India'],
            ['iata_code' => 'IMF', 'airport_name' => 'Imphal ', 'city' => 'Imphal', 'region' => 'Manipur', 'country' => 'India'],
            ['iata_code' => 'IXM', 'airport_name' => 'Madurai ', 'city' => 'Madurai', 'region' => 'Tamil Nadu', 'country' => 'India'],
            ['iata_code' => 'VGA', 'airport_name' => 'Vijayawada Intl ', 'city' => 'Vijayawada', 'region' => 'Andhra Pradesh', 'country' => 'India'],
            ['iata_code' => 'CNN', 'airport_name' => 'Kannur Intl ', 'city' => 'Kannur', 'region' => 'Kerala', 'country' => 'India'],
            ['iata_code' => 'BDQ', 'airport_name' => 'Vadodara ', 'city' => 'Vadodara', 'region' => 'Gujarat', 'country' => 'India'],
            ['iata_code' => 'IXL', 'airport_name' => 'Leh Kushok Bakula Rimpochee ', 'city' => 'Leh', 'region' => 'Ladakh (UT)', 'country' => 'India'],
            ['iata_code' => 'AYJ', 'airport_name' => 'Ayodhya ', 'city' => 'Ayodhya', 'region' => 'Uttar Pradesh', 'country' => 'India'],
            ['iata_code' => 'HSR', 'airport_name' => 'Rajkot Intl ', 'city' => 'Rajkot', 'region' => 'Gujarat', 'country' => 'India'],
            ['iata_code' => 'IXD', 'airport_name' => 'Prayagraj ', 'city' => 'Prayagraj', 'region' => 'Uttar Pradesh', 'country' => 'India'],
            ['iata_code' => 'JDH', 'airport_name' => 'Jodhpur ', 'city' => 'Jodhpur', 'region' => 'Rajasthan', 'country' => 'India'],
            ['iata_code' => 'TIR', 'airport_name' => 'Tirupati ', 'city' => 'Tirupati', 'region' => 'Andhra Pradesh', 'country' => 'India'],
            ['iata_code' => 'GOP', 'airport_name' => 'Gorakhpur ', 'city' => 'Gorakhpur', 'region' => 'Uttar Pradesh', 'country' => 'India'],
            ['iata_code' => 'YYC', 'airport_name' => 'Calgary International ', 'city' => 'Calgary', 'region' => 'Alberta', 'country' => 'Canada'],
            ['iata_code' => 'YEG', 'airport_name' => 'Edmonton International ', 'city' => 'Edmonton Metropolitan Region', 'region' => 'Alberta', 'country' => 'Canada'],
            ['iata_code' => 'YFC', 'airport_name' => 'Fredericton International ', 'city' => 'Fredericton', 'region' => 'New Brunswick', 'country' => 'Canada'],
            ['iata_code' => 'YQX', 'airport_name' => 'Gander International ', 'city' => 'Gander', 'region' => 'Newfoundland and Labrador', 'country' => 'Canada'],
            ['iata_code' => 'YHZ', 'airport_name' => 'Halifax Stanfield International ', 'city' => 'Halifax', 'region' => 'Nova Scotia', 'country' => 'Canada'],
            ['iata_code' => 'YQM', 'airport_name' => 'Greater Moncton Roméo LeBlanc International ', 'city' => 'Moncton', 'region' => 'New Brunswick', 'country' => 'Canada'],
            ['iata_code' => 'YUL', 'airport_name' => 'Montréal–Trudeau International ', 'city' => 'Montreal', 'region' => 'Quebec', 'country' => 'Canada'],
            ['iata_code' => 'YOW', 'airport_name' => 'Ottawa Macdonald–Cartier International ', 'city' => 'Ottawa', 'region' => 'Ontario', 'country' => 'Canada'],
            ['iata_code' => 'YQB', 'airport_name' => 'Québec City Jean Lesage International ', 'city' => 'Quebec City', 'region' => 'Quebec', 'country' => 'Canada'],
            ['iata_code' => 'YYT', 'airport_name' => 'St. John\'s International ', 'city' => 'St. John\'s', 'region' => 'Newfoundland and Labrador', 'country' => 'Canada'],
            ['iata_code' => 'YYZ', 'airport_name' => 'Toronto Pearson International ', 'city' => 'Toronto', 'region' => 'Ontario', 'country' => 'Canada'],
            ['iata_code' => 'YVR', 'airport_name' => 'Vancouver International ', 'city' => 'Vancouver', 'region' => 'British Columbia', 'country' => 'Canada'],
            ['iata_code' => 'YWG', 'airport_name' => 'Winnipeg James Armstrong Richardson International ', 'city' => 'Winnipeg', 'region' => 'Manitoba', 'country' => 'Canada'],
            ['iata_code' => 'DXB', 'airport_name' => 'Dubai Intl ', 'city' => 'Dubai', 'region' => '', 'country' => 'United Arab Emirates'],
            ['iata_code' => 'DOH', 'airport_name' => 'Hamad Intl ', 'city' => 'Doha', 'region' => '', 'country' => 'Qatar'],
            ['iata_code' => 'AUH', 'airport_name' => 'Abu Dhabi Intl ', 'city' => 'Abu Dhabi', 'region' => '', 'country' => 'United Arab Emirates'],
            ['iata_code' => 'RUH', 'airport_name' => 'King Khalid Intl ', 'city' => 'Riyadh', 'region' => '', 'country' => 'Saudi Arabia'],
            ['iata_code' => 'JED', 'airport_name' => 'King Abdulaziz Intl ', 'city' => 'Jeddah', 'region' => '', 'country' => 'Saudi Arabia'],
            ['iata_code' => 'KWI', 'airport_name' => 'Kuwait Intl ', 'city' => 'Kuwait City', 'region' => '', 'country' => 'Kuwait'],
            ['iata_code' => 'MCT', 'airport_name' => 'Muscat Intl ', 'city' => 'Muscat', 'region' => '', 'country' => 'Oman'],
            ['iata_code' => 'SHJ', 'airport_name' => 'Sharjah Intl ', 'city' => 'Sharjah', 'region' => '', 'country' => 'United Arab Emirates'],
            ['iata_code' => 'BAH', 'airport_name' => 'Bahrain Intl ', 'city' => 'Manama', 'region' => '', 'country' => 'Bahrain'],
            ['iata_code' => 'LHR', 'airport_name' => 'London Heathrow ', 'city' => 'London', 'region' => '', 'country' => 'United Kingdom'],
            ['iata_code' => 'FRA', 'airport_name' => 'Frankfurt ', 'city' => 'Frankfurt', 'region' => '', 'country' => 'Germany'],
            ['iata_code' => 'MUC', 'airport_name' => 'Munich ', 'city' => 'Munich', 'region' => '', 'country' => 'Germany'],
            ['iata_code' => 'AMS', 'airport_name' => 'Amsterdam Schiphol ', 'city' => 'Amsterdam', 'region' => '', 'country' => 'Netherlands'],
            ['iata_code' => 'CDG', 'airport_name' => 'Paris Charles de Gaulle ', 'city' => 'Paris', 'region' => '', 'country' => 'France'],
            ['iata_code' => 'IST', 'airport_name' => 'Istanbul ', 'city' => 'Istanbul', 'region' => '', 'country' => 'Turkey'],
            ['iata_code' => 'ZRH', 'airport_name' => 'Zurich ', 'city' => 'Zurich', 'region' => '', 'country' => 'Switzerland'],
            ['iata_code' => 'VIE', 'airport_name' => 'Vienna Intl ', 'city' => 'Vienna', 'region' => '', 'country' => 'Austria'],
            ['iata_code' => 'FCO', 'airport_name' => 'Rome Fiumicino ', 'city' => 'Rome', 'region' => '', 'country' => 'Italy'],
            ['iata_code' => 'MAD', 'airport_name' => 'Madrid Barajas ', 'city' => 'Madrid', 'region' => '', 'country' => 'Spain'],
            ['iata_code' => 'CPH', 'airport_name' => 'Copenhagen ', 'city' => 'Copenhagen', 'region' => '', 'country' => 'Denmark'],
            ['iata_code' => 'BRU', 'airport_name' => 'Brussels ', 'city' => 'Brussels', 'region' => '', 'country' => 'Belgium'],
            ['iata_code' => 'LGW', 'airport_name' => 'London Gatwick ', 'city' => 'London', 'region' => '', 'country' => 'United Kingdom'],
            ['iata_code' => 'HEL', 'airport_name' => 'Helsinki ', 'city' => 'Helsinki', 'region' => '', 'country' => 'Finland'],
            ['iata_code' => 'WAW', 'airport_name' => 'Warsaw Chopin ', 'city' => 'Warsaw', 'region' => '', 'country' => 'Poland'],
            ['iata_code' => 'SIN', 'airport_name' => 'Singapore Changi ', 'city' => 'Singapore', 'region' => '', 'country' => 'Singapore'],
            ['iata_code' => 'HKG', 'airport_name' => 'Hong Kong Intl ', 'city' => 'Hong Kong', 'region' => '', 'country' => 'Hong Kong SAR'],
            ['iata_code' => 'ICN', 'airport_name' => 'Seoul Incheon Intl ', 'city' => 'Seoul', 'region' => '', 'country' => 'South Korea'],
            ['iata_code' => 'NRT', 'airport_name' => 'Tokyo Narita Intl ', 'city' => 'Tokyo', 'region' => '', 'country' => 'Japan'],
            ['iata_code' => 'HND', 'airport_name' => 'Tokyo Haneda ', 'city' => 'Tokyo', 'region' => '', 'country' => 'Japan'],
            ['iata_code' => 'KUL', 'airport_name' => 'Kuala Lumpur Intl ', 'city' => 'Kuala Lumpur', 'region' => '', 'country' => 'Malaysia'],
            ['iata_code' => 'BKK', 'airport_name' => 'Bangkok Suvarnabhumi ', 'city' => 'Bangkok', 'region' => '', 'country' => 'Thailand'],
            ['iata_code' => 'MNL', 'airport_name' => 'Manila Ninoy Aquino Intl ', 'city' => 'Manila', 'region' => '', 'country' => 'Philippines'],
            ['iata_code' => 'TPE', 'airport_name' => 'Taipei Taoyuan Intl ', 'city' => 'Taipei', 'region' => '', 'country' => 'Taiwan'],
            ['iata_code' => 'PVG', 'airport_name' => 'Shanghai Pudong Intl ', 'city' => 'Shanghai', 'region' => '', 'country' => 'China'],
            ['iata_code' => 'PEK', 'airport_name' => 'Beijing Capital Intl ', 'city' => 'Beijing', 'region' => '', 'country' => 'China'],
            ['iata_code' => 'CGK', 'airport_name' => 'Jakarta Soekarno-Hatta Intl ', 'city' => 'Jakarta', 'region' => '', 'country' => 'Indonesia'],
            ['iata_code' => 'ADD', 'airport_name' => 'Addis Ababa Bole Intl ', 'city' => 'Addis Ababa', 'region' => '', 'country' => 'Ethiopia'],
            ['iata_code' => 'CAI', 'airport_name' => 'Cairo Intl ', 'city' => 'Cairo', 'region' => '', 'country' => 'Egypt'],
            ['iata_code' => 'JNB', 'airport_name' => 'O.R. Tambo Intl ', 'city' => 'Johannesburg', 'region' => '', 'country' => 'South Africa'],
            ['iata_code' => 'NBO', 'airport_name' => 'Jomo Kenyatta Intl ', 'city' => 'Nairobi', 'region' => '', 'country' => 'Kenya'],
            ['iata_code' => 'TAS', 'airport_name' => 'Tashkent Intl ', 'city' => 'Tashkent', 'region' => '', 'country' => 'Uzbekistan'],
            ['iata_code' => 'ALA', 'airport_name' => 'Almaty Intl ', 'city' => 'Almaty', 'region' => '', 'country' => 'Kazakhstan'],
            ['iata_code' => 'KEF', 'airport_name' => 'Reykjavik Keflavik Intl ', 'city' => 'Reykjavik', 'region' => '', 'country' => 'Iceland'],
        ];

        $popularCodes = ['JFK', 'LAX', 'SFO', 'ORD', 'ATL', 'DFW', 'DEN', 'SEA', 'MCO', 'EWR', 'BOM', 'DEL', 'BLR', 'HYD', 'MAA', 'YYZ', 'YVR', 'YUL'];
        
        $chunks = array_chunk($airports, 50);
        
        foreach ($chunks as $chunk) {
            $data = [];
            foreach ($chunk as $airport) {
                $data[] = [
                    'id' => Str::uuid(),
                    'iata_code' => $airport['iata_code'],
                    'airport_name' => trim($airport['airport_name']),
                    'city' => trim($airport['city']),
                    'region' => trim($airport['region']),
                    'country' => trim($airport['country']),
                    'is_popular' => in_array($airport['iata_code'], $popularCodes),
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
            DB::table('airports')->insert($data);
        }
    }
}
