<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Doctor;
use App\Models\User;

class TwentyDoctorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fetch 20 unique user IDs from the database
        $userIds = User::limit(20)->pluck('id')->toArray();
        $userCount = count($userIds);

        if ($userCount === 0) {
            $this->command->warn('No users found in database. Please run User seeders first.');
            return;
        }

        // 20 realistic doctor profiles with Unsplash portraits
        $doctorsData = [
            [
                'first_name' => 'Sanjay',
                'last_name' => 'Gupta',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223344',
                'headline' => 'Chief Pediatrician & Allergy/Immunology Specialist',
                'bio' => 'Dr. Sanjay Gupta has 12+ years of experience in pediatric asthma, food allergies, and immunotherapy. He specializes in South Asian childhood diet planning and genetic wellness profiles.',
                'primary_specialty' => 'Pediatrics',
                'subspecialties_json' => ['Pediatric Allergy', 'Asthma Care', 'Neonatology'],
                'board_certifications_json' => [['board' => 'American Board of Pediatrics', 'specialty' => 'Pediatrics', 'year_certified' => 2012]],
                'conditions_treated_json' => ['Childhood Asthma', 'Eczema', 'Peanut Allergy', 'Lactose Intolerance'],
                'procedures_json' => ['Allergy Skin Testing', 'Immunotherapy', 'Developmental Screening'],
                'indian_health_specialisations_json' => ['Vegetarian Nutrition Planning', 'Hereditary Conditions (South Asian)'],
                'practice_name' => 'Fremont Pediatrics & Allergy Center',
                'practice_type' => 'group',
                'primary_address_street' => '39100 State St, Suite C',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4001',
                'fax' => '(510) 555-4002',
                'email' => 'dr.sanjay.gupta@fremontpeds.com',
                'website_url' => 'https://www.fremontpeds.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'North Indian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Maulana Azad Medical College (2006) | Residency - Childrens Hospital of Philadelphia (2010)',
                'visiting_parents_care' => false,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.92,
                'review_count' => 31,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Deepa',
                'last_name' => 'Rao',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223345',
                'headline' => 'OB/GYN & South Asian Maternal Health Expert',
                'bio' => 'Dr. Deepa Rao offers comprehensive obstetric and gynecological care. She is passionate about gestational diabetes prevention, PCOS management, and menopause health in South Asian women.',
                'primary_specialty' => 'Obstetrics & Gynecology (OB/GYN)',
                'subspecialties_json' => ['High-Risk Obstetrics', 'Reproductive Endocrinology', 'PCOS Care'],
                'board_certifications_json' => [['board' => 'American Board of Obstetrics and Gynecology', 'specialty' => 'OB/GYN', 'year_certified' => 2014]],
                'conditions_treated_json' => ['PCOS', 'Gestational Diabetes', 'Uterine Fibroids', 'High-Risk Pregnancy'],
                'procedures_json' => ['Ultrasound', 'Colposcopy', 'Minimally Invasive Surgery'],
                'indian_health_specialisations_json' => ['South Asian Diabetes Management', 'Ayurvedic Integration'],
                'practice_name' => 'Metuchen Womens Care',
                'practice_type' => 'group',
                'primary_address_street' => '242 Main St, Suite 2',
                'primary_address_city' => 'Metuchen',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08840',
                'phone' => '(732) 555-4003',
                'fax' => '(732) 555-4004',
                'email' => 'dr.deepa.rao@metuchenwomens.com',
                'website_url' => 'https://www.metuchenwomens.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Oxford'],
                'languages_json' => [['language' => 'Kannada', 'proficiency' => 'Native'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'South Indian',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - Rutgers New Jersey Medical School (2010)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.88,
                'review_count' => 24,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Vikram',
                'last_name' => 'Mehta',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223346',
                'headline' => 'Gastroenterologist & South Asian Celiac/IBS Pioneer',
                'bio' => 'Dr. Vikram Mehta is a board-certified gastroenterologist. He specializes in chronic acid reflux, fatty liver disease, IBS, and tailored colon cancer screenings for vegetarian diets.',
                'primary_specialty' => 'Gastroenterology',
                'subspecialties_json' => ['Hepatology', 'Inflammatory Bowel Disease', 'Therapeutic Endoscopy'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Gastroenterology', 'year_certified' => 2011]],
                'conditions_treated_json' => ['GERD', 'Crohns Disease', 'Celiac Disease', 'Irritable Bowel Syndrome'],
                'procedures_json' => ['Colonoscopy', 'Upper Endoscopy (EGD)', 'Polypectomy'],
                'indian_health_specialisations_json' => ['Vegetarian Nutrition Planning', 'NRI Preventive Screening'],
                'practice_name' => 'Bay Area Digestive Wellness',
                'practice_type' => 'group',
                'primary_address_street' => '1200 Mowry Ave, Suite 101',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4005',
                'fax' => '(510) 555-4006',
                'email' => 'dr.vikram.mehta@baydigestive.com',
                'website_url' => 'https://www.baydigestive.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
                'languages_json' => [['language' => 'Gujarati', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Gujarati',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Grant Medical College Mumbai (2004) | Fellowship - UCLA Medical Center (2010)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.79,
                'review_count' => 19,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Anjali',
                'last_name' => 'Sharma',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223347',
                'headline' => 'Dermatologist & Skin of Color Specialist',
                'bio' => 'Dr. Anjali Sharma is a cosmetic and clinical dermatologist. She specializes in hyperpigmentation, melasma, hair loss (alopecia), and acne treatment in skin of color.',
                'primary_specialty' => 'Dermatology',
                'subspecialties_json' => ['Cosmetic Dermatology', 'Skin of Color', 'Pediatric Dermatology'],
                'board_certifications_json' => [['board' => 'American Board of Dermatology', 'specialty' => 'Dermatology', 'year_certified' => 2016]],
                'conditions_treated_json' => ['Melasma', 'Hyperpigmentation', 'Cystic Acne', 'Psoriasis'],
                'procedures_json' => ['Laser Resurfacing', 'Chemical Peels', 'Mole Removal', 'Biopsy'],
                'indian_health_specialisations_json' => ['Vegetarian Nutrition Planning', 'Ayurvedic Integration'],
                'practice_name' => 'Sharma Dermatology & Aesthetics',
                'practice_type' => 'solo',
                'primary_address_street' => '100 Route 1 South, Suite B',
                'primary_address_city' => 'Woodbridge',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08830',
                'phone' => '(732) 555-4007',
                'fax' => '(732) 555-4008',
                'email' => 'contact@sharmaderm.com',
                'website_url' => 'https://www.sharmaderm.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY', 'PA'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'North Indian',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - Columbia University Vagelos College of Physicians and Surgeons (2012)',
                'visiting_parents_care' => false,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.95,
                'review_count' => 45,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Amit',
                'last_name' => 'Choudhury',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223348',
                'headline' => 'Orthopedic Surgeon & Joint Replacement Specialist',
                'bio' => 'Dr. Amit Choudhury is a fellowship-trained orthopedic surgeon specializing in minimally invasive total hip and knee replacements, sports injuries, and arthritis management.',
                'primary_specialty' => 'Orthopedic Surgery',
                'subspecialties_json' => ['Joint Reconstruction', 'Sports Medicine', 'Fracture Care'],
                'board_certifications_json' => [['board' => 'American Board of Orthopaedic Surgery', 'specialty' => 'Orthopedic Surgery', 'year_certified' => 2013]],
                'conditions_treated_json' => ['Knee Osteoarthritis', 'Meniscus Tear', 'Rotator Cuff Tear', 'Hip Arthritis'],
                'procedures_json' => ['Total Knee Replacement', 'Knee Arthroscopy', 'Joint Injections'],
                'indian_health_specialisations_json' => ['Hereditary Conditions (South Asian)'],
                'practice_name' => 'Choudhury Orthopedics & Joint Institute',
                'practice_type' => 'group',
                'primary_address_street' => '2200 Southwest Fwy, Suite 104',
                'primary_address_city' => 'Sugar Land',
                'primary_address_state' => 'TX',
                'primary_address_zip' => '77478',
                'phone' => '(281) 555-4009',
                'fax' => '(281) 555-4010',
                'email' => 'info@choudhuryortho.com',
                'website_url' => 'https://www.choudhuryortho.com',
                'telehealth_available' => false,
                'telehealth_states_json' => ['TX'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Humana', 'Medicare'],
                'languages_json' => [['language' => 'Bengali', 'proficiency' => 'Native'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Bengali',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - Baylor College of Medicine (2007) | Fellowship - Hospital for Special Surgery NY (2012)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.86,
                'review_count' => 28,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Meera',
                'last_name' => 'Krishnan',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223349',
                'headline' => 'Neurologist & South Asian Stroke Prevention Advocate',
                'bio' => 'Dr. Meera Krishnan specializes in neuromuscular disorders, migraine management, dementia diagnostic plans, and hereditary stroke risk factor prevention.',
                'primary_specialty' => 'Neurology',
                'subspecialties_json' => ['Headache Medicine', 'Clinical Neurophysiology', 'Stroke Care'],
                'board_certifications_json' => [['board' => 'American Board of Psychiatry and Neurology', 'specialty' => 'Neurology', 'year_certified' => 2015]],
                'conditions_treated_json' => ['Migraine', 'Neuropathy', 'Alzheimers Disease', 'Stroke'],
                'procedures_json' => ['EMG/NCS Testing', 'Botox for Migraine', 'EEG Reading'],
                'indian_health_specialisations_json' => ['Hereditary Conditions (South Asian)', 'India Medical Document Translation'],
                'practice_name' => 'Sugar Land Neurology Clinic',
                'practice_type' => 'group',
                'primary_address_street' => '17510 W Grand Pkwy S, Suite 400',
                'primary_address_city' => 'Sugar Land',
                'primary_address_state' => 'TX',
                'primary_address_zip' => '77479',
                'phone' => '(281) 555-4011',
                'fax' => '(281) 555-4012',
                'email' => 'contact@sugarlandneuro.com',
                'website_url' => 'https://www.sugarlandneuro.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['TX'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Humana', 'Medicare'],
                'languages_json' => [['language' => 'Malayalam', 'proficiency' => 'Native'], ['language' => 'Tamil', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'South Indian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Government Medical College Trivandrum (2007) | Residency - Cleveland Clinic (2012)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.90,
                'review_count' => 17,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Rajeev',
                'last_name' => 'Bhatia',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223350',
                'headline' => 'Psychiatrist & Cultural Integration Counselor',
                'bio' => 'Dr. Rajeev Bhatia offers compassionate mental health treatment, blending evidence-based psychiatry with a deep understanding of South Asian cultural dynamics, family expectations, and anxiety.',
                'primary_specialty' => 'Psychiatry',
                'subspecialties_json' => ['Anxiety Disorders', 'Adolescent Psychiatry', 'Mood Disorders'],
                'board_certifications_json' => [['board' => 'American Board of Psychiatry and Neurology', 'specialty' => 'Psychiatry', 'year_certified' => 2010]],
                'conditions_treated_json' => ['Depression', 'Generalized Anxiety', 'ADHD', 'PTSD'],
                'procedures_json' => ['Psychopharmacology', 'Cognitive Behavioral Therapy (CBT)', 'Tele-Psychiatry'],
                'indian_health_specialisations_json' => ['Ayurvedic Integration'],
                'practice_name' => 'Mind & Body Cultural Wellness',
                'practice_type' => 'solo',
                'primary_address_street' => '39200 Liberty St, Suite D',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4013',
                'fax' => '(510) 555-4014',
                'email' => 'dr.bhatia@mindbodywellness.com',
                'website_url' => 'https://www.mindbodywellness.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA', 'TX', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare'],
                'languages_json' => [['language' => 'Punjabi', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Punjabi',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - UT Southwestern Medical Center (2005)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.82,
                'review_count' => 21,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Kavita',
                'last_name' => 'Joshi',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223351',
                'headline' => 'Endocrinologist & Diabetes Reversal Specialist',
                'bio' => 'Dr. Kavita Joshi is specialized in hormone health, thyroid disorders, and advanced South Asian diabetes reversal tracks using diet modifications and fasting planning.',
                'primary_specialty' => 'Endocrinology',
                'subspecialties_json' => ['Thyroid Care', 'Metabolic Disorders', 'Diabetes Care'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Endocrinology', 'year_certified' => 2013]],
                'conditions_treated_json' => ['Type 2 Diabetes', 'Hypothyroidism', 'PCOS', 'Osteoporosis'],
                'procedures_json' => ['Continuous Glucose Monitoring', 'Insulin Pump Therapy', 'Thyroid Ultrasound'],
                'indian_health_specialisations_json' => ['South Asian Diabetes Management', 'Festival Fasting & Medication Timing'],
                'practice_name' => 'Joshi Endocrinology Associates',
                'practice_type' => 'group',
                'primary_address_street' => '2005 Route 27, Suite A',
                'primary_address_city' => 'Edison',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08817',
                'phone' => '(732) 555-4015',
                'fax' => '(732) 555-4016',
                'email' => 'dr.kjoshi@joshiendo.com',
                'website_url' => 'https://www.joshiendo.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Medicare'],
                'languages_json' => [['language' => 'Marathi', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Maharashtrian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Seth G.S. Medical College Mumbai (2005) | Residency - Albert Einstein College of Medicine (2009)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.91,
                'review_count' => 38,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Rahul',
                'last_name' => 'Kapoor',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223352',
                'headline' => 'Pulmonologist & Sleep Apnea Specialist',
                'bio' => 'Dr. Rahul Kapoor treats complex lung conditions, asthma, COPD, and obstructive sleep apnea, with tailored diagnostic sleep clinics and high-altitude flight clearance consults.',
                'primary_specialty' => 'Pulmonology',
                'subspecialties_json' => ['Sleep Medicine', 'Critical Care Medicine', 'COPD Care'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Pulmonary Disease', 'year_certified' => 2011]],
                'conditions_treated_json' => ['COPD', 'Sleep Apnea', 'Asthma', 'Chronic Cough'],
                'procedures_json' => ['Bronchoscopy', 'Pulmonary Function Test (PFT)', 'Sleep Study Integration'],
                'indian_health_specialisations_json' => ['NRI Preventive Screening'],
                'practice_name' => 'Silicon Valley Pulmonary Clinic',
                'practice_type' => 'group',
                'primary_address_street' => '39210 Liberty St, Suite C',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4017',
                'fax' => '(510) 555-4018',
                'email' => 'dr.kapoor@svpulmonary.com',
                'website_url' => 'https://www.svpulmonary.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Native'], ['language' => 'Punjabi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1637059824899-a441006a6875?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Punjabi',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Christian Medical College Ludhiana (2003) | Fellowship - Boston University (2009)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.84,
                'review_count' => 15,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Sunita',
                'last_name' => 'Nair',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223353',
                'headline' => 'Nephrologist & Chronic Kidney Care Specialist',
                'bio' => 'Dr. Sunita Nair provides advanced care for chronic kidney disease, hypertension, vegetarian renal diet mapping, and dialysis management.',
                'primary_specialty' => 'Nephrology',
                'subspecialties_json' => ['Glomerular Diseases', 'Hypertension Management', 'Dialysis Care'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Nephrology', 'year_certified' => 2012]],
                'conditions_treated_json' => ['CKD', 'Kidney Stones', 'Hypertension', 'Proteinuria'],
                'procedures_json' => ['Dialysis Supervision', 'Kidney Biopsy Interpretations'],
                'indian_health_specialisations_json' => ['South Asian Diabetes Management', 'Vegetarian Nutrition Planning'],
                'practice_name' => 'Edison Nephrology & Hypertension',
                'practice_type' => 'group',
                'primary_address_street' => '2070 Route 27, Suite C',
                'primary_address_city' => 'Edison',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08817',
                'phone' => '(732) 555-4019',
                'fax' => '(732) 555-4020',
                'email' => 'dr.nair@edisonnephrology.com',
                'website_url' => 'https://www.edisonnephrology.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY', 'PA'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Medicare'],
                'languages_json' => [['language' => 'Malayalam', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'South Indian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Kasturba Medical College Manipal (2004) | Fellowship - University of Pennsylvania (2010)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.77,
                'review_count' => 12,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Arun',
                'last_name' => 'Varma',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223354',
                'headline' => 'Oncologist & South Asian Hereditary Cancer Researcher',
                'bio' => 'Dr. Arun Varma specializes in solid tumors, hematology, and screening protocols tailored for South Asian families with genetic cancer syndromes.',
                'primary_specialty' => 'Oncology',
                'subspecialties_json' => ['Hematology', 'Breast Cancer', 'Hereditary Cancer Genetics'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Medical Oncology', 'year_certified' => 2011]],
                'conditions_treated_json' => ['Lymphoma', 'Breast Cancer', 'Colon Cancer', 'Anemia'],
                'procedures_json' => ['Chemotherapy Management', 'Bone Marrow Biopsy'],
                'indian_health_specialisations_json' => ['Hereditary Conditions (South Asian)', 'India Medical Document Translation'],
                'practice_name' => 'Varma Cancer Center',
                'practice_type' => 'group',
                'primary_address_street' => '16605 Southwest Fwy, Suite 101',
                'primary_address_city' => 'Sugar Land',
                'primary_address_state' => 'TX',
                'primary_address_zip' => '77479',
                'phone' => '(281) 555-4021',
                'fax' => '(281) 555-4022',
                'email' => 'dr.varma@varmacancer.com',
                'website_url' => 'https://www.varmacancer.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['TX'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Humana', 'Medicare'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1582750433449-64c656df174f?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Keralite',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - UTHealth Houston (2005) | Fellowship - MD Anderson Cancer Center (2010)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.93,
                'review_count' => 20,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Sandhya',
                'last_name' => 'Iyer',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223355',
                'headline' => 'Rheumatologist & Joint Inflammatory Specialist',
                'bio' => 'Dr. Sandhya Iyer treats Rheumatoid Arthritis, Lupus, Gout, and autoimmune disorders, emphasizing holistic stress reduction and yoga modifications.',
                'primary_specialty' => 'Rheumatology',
                'subspecialties_json' => ['Autoimmune Diseases', 'Arthritis Management', 'Osteoporosis Care'],
                'board_certifications_json' => [['board' => 'American Board of Internal Medicine', 'specialty' => 'Rheumatology', 'year_certified' => 2013]],
                'conditions_treated_json' => ['Rheumatoid Arthritis', 'Systemic Lupus', 'Psoriatic Arthritis', 'Gout'],
                'procedures_json' => ['Joint Injections', 'Infusion Therapy Supervision', 'Ultrasound Guidance'],
                'indian_health_specialisations_json' => ['Ayurvedic Integration'],
                'practice_name' => 'Iyer Autoimmune & Joint Health',
                'practice_type' => 'solo',
                'primary_address_street' => '224 Main St, Suite A',
                'primary_address_city' => 'Metuchen',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08840',
                'phone' => '(732) 555-4023',
                'fax' => '(732) 555-4024',
                'email' => 'dr.iyer@iyerrheumatology.com',
                'website_url' => 'https://www.iyerrheumatology.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare'],
                'languages_json' => [['language' => 'Tamil', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Tamil Brahmin',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - SUNY Downstate College of Medicine (2009)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.87,
                'review_count' => 16,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Rohan',
                'last_name' => 'Sinha',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223356',
                'headline' => 'Otolaryngologist (ENT) & Pediatric Hearing Specialist',
                'bio' => 'Dr. Rohan Sinha is a pediatric and adult ENT specialist treating sinus disease, sleep disorders, tonsillitis, and chronic ear infections.',
                'primary_specialty' => 'Otolaryngology (ENT)',
                'subspecialties_json' => ['Pediatric Otolaryngology', 'Rhinology & Sinus Surgery', 'Hearing Loss Care'],
                'board_certifications_json' => [['board' => 'American Board of Otolaryngology', 'specialty' => 'Otolaryngology', 'year_certified' => 2014]],
                'conditions_treated_json' => ['Sinusitis', 'Deviated Septum', 'Hearing Loss', 'Sleep Apnea'],
                'procedures_json' => ['Septoplasty', 'Tonsillectomy', 'Sinus Surgery', 'Ear Tube Placement'],
                'indian_health_specialisations_json' => ['NRI Preventive Screening'],
                'practice_name' => 'Sinha ENT & Allergy Associates',
                'practice_type' => 'group',
                'primary_address_street' => '39220 Liberty St, Suite A',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4025',
                'fax' => '(510) 555-4026',
                'email' => 'dr.sinha@sinhaent.com',
                'website_url' => 'https://www.sinhaent.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Native'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'North Indian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - AIIMS New Delhi (2007) | Residency - Johns Hopkins Hospital (2012)',
                'visiting_parents_care' => false,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.90,
                'review_count' => 22,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Aarti',
                'last_name' => 'Patel',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223357',
                'headline' => 'Ophthalmologist & Diabetic Retinopathy Expert',
                'bio' => 'Dr. Aarti Patel provides specialized medical and surgical eye care. She has extensive experience in diabetic retinopathy, glaucoma management, and cataract surgery.',
                'primary_specialty' => 'Ophthalmology',
                'subspecialties_json' => ['Medical Retina', 'Cataract Surgery', 'Glaucoma Management'],
                'board_certifications_json' => [['board' => 'American Board of Ophthalmology', 'specialty' => 'Ophthalmology', 'year_certified' => 2012]],
                'conditions_treated_json' => ['Diabetic Retinopathy', 'Cataracts', 'Glaucoma', 'Dry Eye Syndrome'],
                'procedures_json' => ['Cataract Surgery', 'Intravitreal Injections', 'Laser Eye Surgery'],
                'indian_health_specialisations_json' => ['South Asian Diabetes Management'],
                'practice_name' => 'Patel Eye Surgeons',
                'practice_type' => 'group',
                'primary_address_street' => '2075 Route 27, Suite B',
                'primary_address_city' => 'Edison',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08817',
                'phone' => '(732) 555-4027',
                'fax' => '(732) 555-4028',
                'email' => 'dr.apatel@pateleyesurgeons.com',
                'website_url' => 'https://www.pateleyesurgeons.com',
                'telehealth_available' => false,
                'telehealth_states_json' => ['NJ'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Medicare'],
                'languages_json' => [['language' => 'Gujarati', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Gujarati',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - UT Southwestern Medical Center (2007) | Fellowship - Wills Eye Hospital Philadelphia (2011)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.89,
                'review_count' => 33,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Karan',
                'last_name' => 'Malhotra',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223358',
                'headline' => 'Allergist & Immunology Specialist',
                'bio' => 'Dr. Karan Malhotra specializes in environmental allergy testing, pediatric food challenges, medication desensitisation, and chronic hives treatment.',
                'primary_specialty' => 'Allergy & Immunology',
                'subspecialties_json' => ['Food Allergy', 'Asthma Care', 'Medication Allergy'],
                'board_certifications_json' => [['board' => 'American Board of Allergy and Immunology', 'specialty' => 'Allergy & Immunology', 'year_certified' => 2015]],
                'conditions_treated_json' => ['Allergic Rhinitis', 'Asthma', 'Peanut Allergy', 'Hives'],
                'procedures_json' => ['Skin Testing', 'Food Challenge', 'Patch Testing', 'Immunotherapy Injection'],
                'indian_health_specialisations_json' => ['Vegetarian Nutrition Planning'],
                'practice_name' => 'Malhotra Allergy & Asthma Specialists',
                'practice_type' => 'solo',
                'primary_address_street' => '16555 Southwest Fwy, Suite 104',
                'primary_address_city' => 'Sugar Land',
                'primary_address_state' => 'TX',
                'primary_address_zip' => '77479',
                'phone' => '(281) 555-4029',
                'fax' => '(281) 555-4030',
                'email' => 'dr.karan@malhotraallergy.com',
                'website_url' => 'https://www.malhotraallergy.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['TX'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Humana'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Native'], ['language' => 'Punjabi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'North Indian',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - University of Michigan Medical School (2011)',
                'visiting_parents_care' => false,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.91,
                'review_count' => 19,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Meenakshi',
                'last_name' => 'Pillai',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223359',
                'headline' => 'Interventional Pain Management Specialist',
                'bio' => 'Dr. Meenakshi Pillai is dedicated to non-surgical treatment of spinal pain, nerve injuries, arthritis, and chronic musculoskeletal pain syndromes.',
                'primary_specialty' => 'Pain Management',
                'subspecialties_json' => ['Interventional Spine Care', 'Joint Injections', 'Neuropathy Treatment'],
                'board_certifications_json' => [['board' => 'American Board of Anesthesiology', 'specialty' => 'Pain Medicine', 'year_certified' => 2013]],
                'conditions_treated_json' => ['Sciatica', 'Herniated Disc', 'Back Pain', 'Osteoarthritis'],
                'procedures_json' => ['Epidural Steroid Injection', 'Facet Joint Injection', 'Radiofrequency Ablation'],
                'indian_health_specialisations_json' => ['Ayurvedic Integration'],
                'practice_name' => 'Metuchen Pain & Spine Center',
                'practice_type' => 'group',
                'primary_address_street' => '240 Main St, Suite 1',
                'primary_address_city' => 'Metuchen',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08840',
                'phone' => '(732) 555-4031',
                'fax' => '(732) 555-4032',
                'email' => 'dr.pillai@metuchenpain.com',
                'website_url' => 'https://www.metuchenpain.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare'],
                'languages_json' => [['language' => 'Tamil', 'proficiency' => 'Native'], ['language' => 'Malayalam', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'South Indian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Amrita School of Medicine Kochi (2005) | Residency - Rutgers New Jersey Medical School (2010)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.85,
                'review_count' => 14,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Vikram',
                'last_name' => 'Sen',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223360',
                'headline' => 'Physical Medicine & Rehabilitation Specialist',
                'bio' => 'Dr. Vikram Sen focuses on physical restoration, stroke rehabilitation, sports injuries, and conservative neck and back pain therapies.',
                'primary_specialty' => 'Physical Medicine & Rehabilitation',
                'subspecialties_json' => ['Stroke Rehab', 'Sports Injury Rehab', 'Spine Rehabilitation'],
                'board_certifications_json' => [['board' => 'American Board of Physical Medicine and Rehabilitation', 'specialty' => 'Physical Medicine & Rehab', 'year_certified' => 2011]],
                'conditions_treated_json' => ['Stroke Recovery', 'Carpal Tunnel Syndrome', 'Spinal Cord Injury', 'Spasticity'],
                'procedures_json' => ['EMG/NCS Diagnostic Studies', 'Trigger Point Injections', 'Joint Aspiration'],
                'indian_health_specialisations_json' => ['Ayurvedic Integration', 'Visiting Parents Care'],
                'practice_name' => 'Fremont Rehab Specialists',
                'practice_type' => 'group',
                'primary_address_street' => '39230 Liberty St, Suite B',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4033',
                'fax' => '(510) 555-4034',
                'email' => 'contact@fremontrehab.com',
                'website_url' => 'https://www.fremontrehab.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
                'languages_json' => [['language' => 'Bengali', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Bengali',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Medical College Kolkata (2004) | Residency - Northwestern Memorial Hospital (2009)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.79,
                'review_count' => 11,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Meera',
                'last_name' => 'Nambiar',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223361',
                'headline' => 'Vascular Surgeon & Leg Pain/Varicose Expert',
                'bio' => 'Dr. Meera Nambiar treats peripheral arterial disease, varicose veins, deep vein thrombosis, and arterial blockages with minimally invasive surgical techniques.',
                'primary_specialty' => 'Vascular Surgery',
                'subspecialties_json' => ['Endovascular Surgery', 'Vein Treatment', 'Diabetic Foot Care'],
                'board_certifications_json' => [['board' => 'American Board of Surgery', 'specialty' => 'Vascular Surgery', 'year_certified' => 2014]],
                'conditions_treated_json' => ['Varicose Veins', 'DVT', 'PAD', 'Aortic Aneurysm'],
                'procedures_json' => ['Endovenous Laser Ablation', 'Sclerotherapy', 'Arterial Angiography'],
                'indian_health_specialisations_json' => ['Hereditary Conditions (South Asian)'],
                'practice_name' => 'Nambiar Vascular & Endovascular Center',
                'practice_type' => 'group',
                'primary_address_street' => '16555 Southwest Fwy, Suite 105',
                'primary_address_city' => 'Sugar Land',
                'primary_address_state' => 'TX',
                'primary_address_zip' => '77479',
                'phone' => '(281) 555-4035',
                'fax' => '(281) 555-4036',
                'email' => 'dr.meera@nambiarvascular.com',
                'website_url' => 'https://www.nambiarvascular.com',
                'telehealth_available' => false,
                'telehealth_states_json' => ['TX'],
                'accepting_new_patients' => true,
                'same_day_available' => false,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Humana', 'Medicare'],
                'languages_json' => [['language' => 'Malayalam', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Keralite',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - UT Southwestern Medical School (2008) | Fellowship - Mayo Clinic Rochester (2013)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.94,
                'review_count' => 25,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Vijay',
                'last_name' => 'Krishnan',
                'credential' => 'MD',
                'gender' => 'male',
                'npi_number' => '1100223362',
                'headline' => 'Urologist & South Asian Prostate Health Specialist',
                'bio' => 'Dr. Vijay Krishnan specializes in prostate health, urinary stone management, minimally invasive vasectomy, and advanced urological cancers.',
                'primary_specialty' => 'Urology',
                'subspecialties_json' => ['Urological Oncology', 'Kidney Stones', 'Male Infertility'],
                'board_certifications_json' => [['board' => 'American Board of Urology', 'specialty' => 'Urology', 'year_certified' => 2012]],
                'conditions_treated_json' => ['Kidney Stones', 'BPH', 'Prostate Cancer', 'Overactive Bladder'],
                'procedures_json' => ['Cystoscopy', 'Lithotripsy (Laser)', 'No-Scalpel Vasectomy'],
                'indian_health_specialisations_json' => ['Hereditary Conditions (South Asian)'],
                'practice_name' => 'Edison Urology Associates',
                'practice_type' => 'group',
                'primary_address_street' => '2075 Route 27, Suite C',
                'primary_address_city' => 'Edison',
                'primary_address_state' => 'NJ',
                'primary_address_zip' => '08817',
                'phone' => '(732) 555-4037',
                'fax' => '(732) 555-4038',
                'email' => 'dr.vijay@edisonurology.com',
                'website_url' => 'https://www.edisonurology.com',
                'telehealth_available' => true,
                'telehealth_states_json' => ['NJ', 'NY'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Medicare'],
                'languages_json' => [['language' => 'Tamil', 'proficiency' => 'Native'], ['language' => 'Hindi', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Tamilian',
                'india_medical_training' => 'mbbs_india_us_residency',
                'india_medical_college' => 'MBBS - Stanley Medical College Chennai (2004) | Residency - New York Presbyterian Hospital (2009)',
                'visiting_parents_care' => true,
                'is_desi_doctor' => true,
                'nri_specialist' => true,
                'avg_rating' => 4.88,
                'review_count' => 30,
                'profile_status' => 'active',
            ],
            [
                'first_name' => 'Shreya',
                'last_name' => 'Ray',
                'credential' => 'MD',
                'gender' => 'female',
                'npi_number' => '1100223363',
                'headline' => 'General Surgeon & Advanced Laparoscopy Expert',
                'bio' => 'Dr. Shreya Ray offers expert general and advanced laparoscopic surgical services. She specializes in gallbladder removals, hernia repair, and appendectomies.',
                'primary_specialty' => 'General Surgery',
                'subspecialties_json' => ['Minimally Invasive Surgery', 'Hernia Repair', 'Gallbladder Care'],
                'board_certifications_json' => [['board' => 'American Board of Surgery', 'specialty' => 'General Surgery', 'year_certified' => 2013]],
                'conditions_treated_json' => ['Gallstones', 'Inguinal Hernia', 'Appendicitis', 'Lipoma'],
                'procedures_json' => ['Laparoscopic Cholecystectomy', 'Laparoscopic Hernia Repair', 'Biopsy'],
                'indian_health_specialisations_json' => ['NRI Preventive Screening'],
                'practice_name' => 'Silicon Valley Surgical Care',
                'practice_type' => 'group',
                'primary_address_street' => '39240 Liberty St, Suite A',
                'primary_address_city' => 'Fremont',
                'primary_address_state' => 'CA',
                'primary_address_zip' => '94538',
                'phone' => '(510) 555-4039',
                'fax' => '(510) 555-4040',
                'email' => 'dr.shreya@svsurgical.com',
                'website_url' => 'https://www.svsurgical.com',
                'telehealth_available' => false,
                'telehealth_states_json' => ['CA'],
                'accepting_new_patients' => true,
                'same_day_available' => true,
                'insurance_plans_json' => ['Blue Cross Blue Shield', 'Aetna', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
                'languages_json' => [['language' => 'Hindi', 'proficiency' => 'Native'], ['language' => 'Bengali', 'proficiency' => 'Fluent'], ['language' => 'English', 'proficiency' => 'Native']],
                'profile_photo_url' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&h=256&q=80',
                'cultural_background' => 'Bengali',
                'india_medical_training' => 'us_medical_school',
                'india_medical_college' => 'MD - Harvard Medical School (2007) | Residency - Massachusetts General Hospital (2012)',
                'visiting_parents_care' => false,
                'is_desi_doctor' => true,
                'nri_specialist' => false,
                'avg_rating' => 4.92,
                'review_count' => 18,
                'profile_status' => 'active',
            ],
        ];

        // Seed each doctor profile
        foreach ($doctorsData as $index => $data) {
            // Distribute among the 20 fetched user IDs round-robin (safe fallback)
            $userId = $userIds[$index % $userCount];

            // Build slug matching the format: {first_name}-{last_name}-{city}-{state}-{zipcode}
            $firstNameSlug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $data['first_name']));
            $lastNameSlug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $data['last_name']));
            $citySlug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $data['primary_address_city']));
            $stateSlug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $data['primary_address_state']));
            $zipSlug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $data['primary_address_zip']));

            $data['slug'] = "{$firstNameSlug}-{$lastNameSlug}-{$citySlug}-{$stateSlug}-{$zipSlug}";
            $data['user_id'] = $userId;
            $data['npi_verified'] = true;
            $data['npi_verified_at' ] = now();

            $doctor = Doctor::create($data);

            // Create a default hospital affiliation
            $doctor->affiliations()->create([
                'facility_name' => "{$data['practice_name']} Affiliated Hospital",
                'facility_type' => 'hospital',
                'affiliation_type' => 'admitting',
                'address_street' => $data['primary_address_street'],
                'address_city' => $data['primary_address_city'],
                'address_state' => $data['primary_address_state'],
                'address_zip' => $data['primary_address_zip'],
                'phone' => $data['phone'],
                'cms_star_rating' => 4.5,
            ]);

            // Create a default Top Doctor award
            $doctor->awards()->create([
                'award_name' => 'Castle Connolly Top Doctor',
                'award_type' => 'castle_connolly',
                'awarding_org' => 'Castle Connolly Medical Ltd.',
                'years_json' => [2024, 2025],
            ]);
        }

        $this->command->info('Successfully seeded 20 realistic doctor profiles!');
    }
}
