name: Delete DB Old Records News Crawler

on:
  schedule:
    # Runs once a day at 12 midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'desipath-crawler/package-lock.json'

      - name: Install Dependencies
        working-directory: ./desipath-crawler
        run: npm ci

      - name: Run Cleanup Script
        working-directory: ./desipath-crawler
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: node src/cleanup.js
